# Setting up R and RStudio

Every journey starts with gathering the right equipment. This intellectual journey is not much different. The first step that every '*R* novice has to face is to set everything up to get started. There are essentially two strategies:

-   Install [*R*](https://www.r-project.org "R"){target="_blank"}and [RStudio](https://www.rstudio.com "RStudio"){target="_blank"}

or

-   Run RStudio in a browser via [RStudio Cloud](https://rstudio.cloud "RStudio Cloud"){target="_blank"}

While installing *R* and Studio requires more time and effort, I strongly recommend it, especially if you want to work offline or make good use of your computer's CPU. However, if you are not sure yet whether you enjoy learning *R*, you might wish to look at RStudio Cloud first. Either way, you can follow the examples of this book no matter which choice you make.

## Installing R

The core module of our programming is R itself, and since it is an open-source project, it is available for free on Windows, Mac and Linux computers. Here is what you need to do to install it properly on your computer of choice:

1\. Go to [www.r-project.org](https://www.r-project.org](https://www.r-project.org) "www.r-project.org"){target="_blank"}

2\. Click on 'CRAN' where it says download.

3\. Choose a server in your country (all of them work, but downloads will perform quicker)

4\. Select the version you want to install (I recommend the latest version)

5\. Open the downloaded file and follow the installation instructions. (I recommend leaving the suggested settings as they are).

(INSERT IMAGES ABOUT HERE)

This was relatively easy. You now have *R* installed. Technically you can start using *R* for your research, but there is one more tool I strongly advise installing: RStudio.

## Installing RStudio

*R* by itself is just the \*'beating heart'\* of *R* programming, but it has no particular user interface. If you want buttons to click and actually 'see' what you are doing, there is no better way than RStudio. It will be the primary tool to interact with *R* and the only software you need to do all the fun parts. To install RStudio perform the following steps:

1.  Go to [www.rstudio.com](https://www.rstudio.com](https://www.rstudio.com) "www.rstudio.com"){target="_blank"}.

2.  Go to Products \> RStudio

3.  On this page, select RStudio Desktop

4.  Select the \*'free'\* option and begin the download

5.  Open the downloaded file and follow the installation instructions (again, keep it to the default settings as much as possible)

Congratulations, you are all set up to learn R.

## When you first start RStudio

You are all set up to get started, but if you want the best experience, you might want to make some tweaks to your settings. I recommend at least the following two by clicking on \*RStudio \> Preferences \> Code\*:

1.  In the \*'Editing'\* tab, make sure to have at least the first four options ticked, especially the 'Auto-indent code after paste'. This setting will save time when trying to format your coding appropriately, making it easier to read.

(INSERT IMAGE)

2.  In the \*'Display'\* tab, you might want to have the first three options selected. In particular, \*'Highlight selected line'\* is helpful because, in more complicated code, it is helpful to see where your cursor is.

Finally, everything is ready, and we can get to the most exciting part of this post.

## Updating R and RStudio: Living at the pulse of innovation 

While not strictly something that helps you become a better programmer, this advice might come in handy to avoid becoming a frustrated programmer. When you update your software, you need to update R and RStudio separately from each other. While both R and RStudio work closely with each other, they still constitute separate pieces of software. Thus, it is important to keep in mind that updating RStudio will not automatically update R. This can become problematic if specific packages you installed via RStudio (like a fancy learning algorithm) might not be compatible with earlier versions of R. Also, additional R packages developed by other people are separate pieces and are updated too, independently from R and RStudio.

I know what you are thinking: This already sounds complicated and cumbersome. However, rest assured, we take a look at how you can easily update all your packages with RStudio itself. Thus, all you need to remember is: *R* needs to be updated separately from everything else. Enough of spoiling future posts, back to *R* and RStudio. It is time to take a closer look at it by finally opening RStudio.

## RStudio Cloud
