<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 Correlations | R for Non-Programmers: A Guide for Social Scientists</title>
  <meta name="description" content="10 Correlations | R for Non-Programmers: A Guide for Social Scientists is a springboard into the world of R without having to become a full-fledged R programmer or possess abundant knowledge in other programming languages. This book guides you through the most common challenges in empirical research in the Social Sciences and offers practical and efficient solutions. Each chapter is dedicated to a common task we have to achieve to answer our research questions. In addition, it provides plenty of exercises and in-depth case studies based on actual data." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="10 Correlations | R for Non-Programmers: A Guide for Social Scientists" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://danieldauber.com" />
  <meta property="og:image" content="http://danieldauber.com/images/cover_art_icons/r4np_icon_white_bg_favicon.png" />
  <meta property="og:description" content="10 Correlations | R for Non-Programmers: A Guide for Social Scientists is a springboard into the world of R without having to become a full-fledged R programmer or possess abundant knowledge in other programming languages. This book guides you through the most common challenges in empirical research in the Social Sciences and offers practical and efficient solutions. Each chapter is dedicated to a common task we have to achieve to answer our research questions. In addition, it provides plenty of exercises and in-depth case studies based on actual data." />
  <meta name="github-repo" content="ddauber/r4np_book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 Correlations | R for Non-Programmers: A Guide for Social Scientists" />
  
  <meta name="twitter:description" content="10 Correlations | R for Non-Programmers: A Guide for Social Scientists is a springboard into the world of R without having to become a full-fledged R programmer or possess abundant knowledge in other programming languages. This book guides you through the most common challenges in empirical research in the Social Sciences and offers practical and efficient solutions. Each chapter is dedicated to a common task we have to achieve to answer our research questions. In addition, it provides plenty of exercises and in-depth case studies based on actual data." />
  <meta name="twitter:image" content="http://danieldauber.com/images/cover_art_icons/r4np_icon_white_bg_favicon.png" />

<meta name="author" content="Daniel Dauber" />


<meta name="date" content="2021-09-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/cover_art_icons/r4np_icon_favicon.svg" type="image/x-icon" />
<link rel="prev" href="sources-of-bias.html"/>
<link rel="next" href="power-analysis.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/viz-1.8.2/viz.js"></script>
<link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
<script src="libs/grViz-binding-1.0.6.1/grViz.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for Non-Programmers</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="1" data-path="readme-before-you-get-started.html"><a href="readme-before-you-get-started.html"><i class="fa fa-check"></i><b>1</b> <code>Readme.</code> before you get started</a>
<ul>
<li class="chapter" data-level="1.1" data-path="readme-before-you-get-started.html"><a href="readme-before-you-get-started.html#a-starting-point-and-reference-book"><i class="fa fa-check"></i><b>1.1</b> A starting point and reference book</a></li>
<li class="chapter" data-level="1.2" data-path="readme-before-you-get-started.html"><a href="readme-before-you-get-started.html#download-the-companion-r-package"><i class="fa fa-check"></i><b>1.2</b> Download the companion R package</a></li>
<li class="chapter" data-level="1.3" data-path="readme-before-you-get-started.html"><a href="readme-before-you-get-started.html#a-tidyverse-approach-with-some-basic-r"><i class="fa fa-check"></i><b>1.3</b> A ‘tidyverse’ approach with some basic R</a></li>
<li class="chapter" data-level="1.4" data-path="readme-before-you-get-started.html"><a href="readme-before-you-get-started.html#formatting-of-this-book"><i class="fa fa-check"></i><b>1.4</b> Understanding the formatting of this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="why-learn-a-programming-language-as-a-non-programmer.html"><a href="why-learn-a-programming-language-as-a-non-programmer.html"><i class="fa fa-check"></i><b>2</b> Why learn a programming language as a non-programmer?</a>
<ul>
<li class="chapter" data-level="2.1" data-path="why-learn-a-programming-language-as-a-non-programmer.html"><a href="why-learn-a-programming-language-as-a-non-programmer.html#learning-new-tools-to-analyse-your-data-is-always-essential"><i class="fa fa-check"></i><b>2.1</b> Learning new tools to analyse your data is always essential</a></li>
<li class="chapter" data-level="2.2" data-path="why-learn-a-programming-language-as-a-non-programmer.html"><a href="why-learn-a-programming-language-as-a-non-programmer.html#programming-languages-enhance-your-conceptual-thinking"><i class="fa fa-check"></i><b>2.2</b> Programming languages enhance your conceptual thinking</a></li>
<li class="chapter" data-level="2.3" data-path="why-learn-a-programming-language-as-a-non-programmer.html"><a href="why-learn-a-programming-language-as-a-non-programmer.html#programming-languages-allow-you-to-look-at-your-data-from-a-different-angle"><i class="fa fa-check"></i><b>2.3</b> Programming languages allow you to look at your data from a different angle</a></li>
<li class="chapter" data-level="2.4" data-path="why-learn-a-programming-language-as-a-non-programmer.html"><a href="why-learn-a-programming-language-as-a-non-programmer.html#learning-any-programming-language-will-help-you-learn-other-programming-languages."><i class="fa fa-check"></i><b>2.4</b> Learning any programming language will help you learn other programming languages.</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html"><i class="fa fa-check"></i><b>3</b> Setting up R and RStudio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html#installing-r"><i class="fa fa-check"></i><b>3.1</b> Installing R</a></li>
<li class="chapter" data-level="3.2" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html#installing-rstudio"><i class="fa fa-check"></i><b>3.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="3.3" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html#when-you-first-start-rstudio"><i class="fa fa-check"></i><b>3.3</b> When you first start RStudio</a></li>
<li class="chapter" data-level="3.4" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html#updating-r-and-rstudio"><i class="fa fa-check"></i><b>3.4</b> Updating R and RStudio: Living at the pulse of innovation</a></li>
<li class="chapter" data-level="3.5" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html#rstudio-cloud"><i class="fa fa-check"></i><b>3.5</b> RStudio Cloud</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html"><i class="fa fa-check"></i><b>4</b> The RStudio Interface</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html#the-console-window"><i class="fa fa-check"></i><b>4.1</b> The Console window</a></li>
<li class="chapter" data-level="4.2" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html#the-source-window"><i class="fa fa-check"></i><b>4.2</b> The Source window</a></li>
<li class="chapter" data-level="4.3" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html#the-environment-history-connections-tutorial-window"><i class="fa fa-check"></i><b>4.3</b> The Environment / History / Connections / Tutorial window</a></li>
<li class="chapter" data-level="4.4" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html#the-files-plots-packages-help-viewer-window"><i class="fa fa-check"></i><b>4.4</b> The Files / Plots / Packages / Help / Viewer window</a></li>
<li class="chapter" data-level="4.5" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html#customise-your-user-interface"><i class="fa fa-check"></i><b>4.5</b> Customise your user interface</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html"><i class="fa fa-check"></i><b>5</b> R Basics: The very fundamentals</a>
<ul>
<li class="chapter" data-level="5.1" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#basic-computations-in-r"><i class="fa fa-check"></i><b>5.1</b> Basic computations in R</a></li>
<li class="chapter" data-level="5.2" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#assigning-values-to-objects"><i class="fa fa-check"></i><b>5.2</b> Assigning values to objects: ‘&lt;-’</a></li>
<li class="chapter" data-level="5.3" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#functions"><i class="fa fa-check"></i><b>5.3</b> Functions</a></li>
<li class="chapter" data-level="5.4" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#r-packages"><i class="fa fa-check"></i><b>5.4</b> R packages</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#installing-packages-using-a-function"><i class="fa fa-check"></i><b>5.4.1</b> Installing packages using <code>install.packages()</code></a></li>
<li class="chapter" data-level="5.4.2" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#installing-packages-via-rstudio"><i class="fa fa-check"></i><b>5.4.2</b> Installing packages via RStudio’s package pane</a></li>
<li class="chapter" data-level="5.4.3" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#using-r-packages"><i class="fa fa-check"></i><b>5.4.3</b> Using R Packages</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#coding-etiquette"><i class="fa fa-check"></i><b>5.5</b> Coding etiquette</a></li>
<li class="chapter" data-level="5.6" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#exercises-chapter-5"><i class="fa fa-check"></i><b>5.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="starting-your-r-projects.html"><a href="starting-your-r-projects.html"><i class="fa fa-check"></i><b>6</b> Starting your R projects</a>
<ul>
<li class="chapter" data-level="6.1" data-path="starting-your-r-projects.html"><a href="starting-your-r-projects.html#creating-an-r-project"><i class="fa fa-check"></i><b>6.1</b> Creating an R Project file</a></li>
<li class="chapter" data-level="6.2" data-path="starting-your-r-projects.html"><a href="starting-your-r-projects.html#organising-your-projects"><i class="fa fa-check"></i><b>6.2</b> Organising your projects</a></li>
<li class="chapter" data-level="6.3" data-path="starting-your-r-projects.html"><a href="starting-your-r-projects.html#creating-an-r-script"><i class="fa fa-check"></i><b>6.3</b> Creating an R Script</a></li>
<li class="chapter" data-level="6.4" data-path="starting-your-r-projects.html"><a href="starting-your-r-projects.html#r-markdown-and-r-notebooks"><i class="fa fa-check"></i><b>6.4</b> Using R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i><b>7</b> Data Wrangling and Cleaning</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-wrangling.html"><a href="data-wrangling.html#import-your-data"><i class="fa fa-check"></i><b>7.1</b> Import your data</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="data-wrangling.html"><a href="data-wrangling.html#import-data-from-the-files-pane"><i class="fa fa-check"></i><b>7.1.1</b> Import data from the Files pane</a></li>
<li class="chapter" data-level="7.1.2" data-path="data-wrangling.html"><a href="data-wrangling.html#importing-data-from-the-environment-pane"><i class="fa fa-check"></i><b>7.1.2</b> Importing data from the Environment pane</a></li>
<li class="chapter" data-level="7.1.3" data-path="data-wrangling.html"><a href="data-wrangling.html#importing-data-using-functions"><i class="fa fa-check"></i><b>7.1.3</b> Importing data using functions directly</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="data-wrangling.html"><a href="data-wrangling.html#inspecting-raw-data"><i class="fa fa-check"></i><b>7.2</b> Inspecting your data</a></li>
<li class="chapter" data-level="7.3" data-path="data-wrangling.html"><a href="data-wrangling.html#colnames-cleaning"><i class="fa fa-check"></i><b>7.3</b> Cleaning your column names: Call the <code>janitor</code></a></li>
<li class="chapter" data-level="7.4" data-path="data-wrangling.html"><a href="data-wrangling.html#change-data-types"><i class="fa fa-check"></i><b>7.4</b> Data types: What are they and how can you change them</a></li>
<li class="chapter" data-level="7.5" data-path="data-wrangling.html"><a href="data-wrangling.html#handling-factors"><i class="fa fa-check"></i><b>7.5</b> Handling factors</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="data-wrangling.html"><a href="data-wrangling.html#recoding-factors"><i class="fa fa-check"></i><b>7.5.1</b> Recoding factors</a></li>
<li class="chapter" data-level="7.5.2" data-path="data-wrangling.html"><a href="data-wrangling.html#reordering-factor-levels"><i class="fa fa-check"></i><b>7.5.2</b> Reordering factor levels</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="data-wrangling.html"><a href="data-wrangling.html#dealing-with-missing-data"><i class="fa fa-check"></i><b>7.6</b> Dealing with missing data</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="data-wrangling.html"><a href="data-wrangling.html#mapping-missing-data"><i class="fa fa-check"></i><b>7.6.1</b> Mapping missing data</a></li>
<li class="chapter" data-level="7.6.2" data-path="data-wrangling.html"><a href="data-wrangling.html#patterns-of-missing-data"><i class="fa fa-check"></i><b>7.6.2</b> Identifying patterns of missing data</a></li>
<li class="chapter" data-level="7.6.3" data-path="data-wrangling.html"><a href="data-wrangling.html#replacing-removing-missing-data"><i class="fa fa-check"></i><b>7.6.3</b> Replacing or removing missing data</a></li>
<li class="chapter" data-level="7.6.4" data-path="data-wrangling.html"><a href="data-wrangling.html#main-takeaways-regarding-dealing-with-missing-data"><i class="fa fa-check"></i><b>7.6.4</b> Main takeaways regarding dealing with missing data</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="data-wrangling.html"><a href="data-wrangling.html#latent-constructs"><i class="fa fa-check"></i><b>7.7</b> Latent constructs and their reliability</a></li>
<li class="chapter" data-level="7.8" data-path="data-wrangling.html"><a href="data-wrangling.html#conclusion-data-wrangling"><i class="fa fa-check"></i><b>7.8</b> Once you finished with data wrangling</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>8</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="8.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#plotting-in-r-with-ggplot2"><i class="fa fa-check"></i><b>8.1</b> Plotting in R with <code>ggplot2</code></a></li>
<li class="chapter" data-level="8.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#central-tendency"><i class="fa fa-check"></i><b>8.2</b> Central tendency measures: Mean, Median, Mode</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean"><i class="fa fa-check"></i><b>8.2.1</b> Mean</a></li>
<li class="chapter" data-level="8.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#median"><i class="fa fa-check"></i><b>8.2.2</b> Median</a></li>
<li class="chapter" data-level="8.2.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mode"><i class="fa fa-check"></i><b>8.2.3</b> Mode</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#spread-of-data"><i class="fa fa-check"></i><b>8.3</b> Indicators and visualisations to examine the spread of data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#boxplot-so-much-information-in-just-one-box"><i class="fa fa-check"></i><b>8.3.1</b> Boxplot: So much information in just one box</a></li>
<li class="chapter" data-level="8.3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#histogram-do-not-mistake-it-as-a-bar-plot"><i class="fa fa-check"></i><b>8.3.2</b> Histogram: Do not mistake it as a bar plot</a></li>
<li class="chapter" data-level="8.3.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#density-plots-your-smooth-histograms"><i class="fa fa-check"></i><b>8.3.3</b> Density plots: Your smooth histograms</a></li>
<li class="chapter" data-level="8.3.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#violin-plot-your-smooth-boxplot"><i class="fa fa-check"></i><b>8.3.4</b> Violin plot: Your smooth boxplot</a></li>
<li class="chapter" data-level="8.3.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#qq-plot"><i class="fa fa-check"></i><b>8.3.5</b> QQ plot: A ‘cute’ plot to check for normality in your data</a></li>
<li class="chapter" data-level="8.3.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#standard-deviation"><i class="fa fa-check"></i><b>8.3.6</b> Standard deviation: Your average deviation from the mean</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="sources-of-bias.html"><a href="sources-of-bias.html"><i class="fa fa-check"></i><b>9</b> Sources of bias: Outliers, normality and other ‘conundrums’</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sources-of-bias.html"><a href="sources-of-bias.html#additivity-and-linearity"><i class="fa fa-check"></i><b>9.1</b> Linearity and additivity</a></li>
<li class="chapter" data-level="9.2" data-path="sources-of-bias.html"><a href="sources-of-bias.html#independence"><i class="fa fa-check"></i><b>9.2</b> Independence</a></li>
<li class="chapter" data-level="9.3" data-path="sources-of-bias.html"><a href="sources-of-bias.html#normality"><i class="fa fa-check"></i><b>9.3</b> Normality</a></li>
<li class="chapter" data-level="9.4" data-path="sources-of-bias.html"><a href="sources-of-bias.html#homogeneity-of-variance"><i class="fa fa-check"></i><b>9.4</b> Homogeneity of variance (homoscedasticity)</a></li>
<li class="chapter" data-level="9.5" data-path="sources-of-bias.html"><a href="sources-of-bias.html#dealing-with-outliers"><i class="fa fa-check"></i><b>9.5</b> Outliers and how to deal with them</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="sources-of-bias.html"><a href="sources-of-bias.html#ouliers-standard_deviation"><i class="fa fa-check"></i><b>9.5.1</b> Detecting outliers using the standard deviation</a></li>
<li class="chapter" data-level="9.5.2" data-path="sources-of-bias.html"><a href="sources-of-bias.html#outliers-iqr"><i class="fa fa-check"></i><b>9.5.2</b> Detecting outliers using the interquartile range</a></li>
<li class="chapter" data-level="9.5.3" data-path="sources-of-bias.html"><a href="sources-of-bias.html#removing-or-replacing-outliers"><i class="fa fa-check"></i><b>9.5.3</b> Removing or replacing outliers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlations.html"><a href="correlations.html"><i class="fa fa-check"></i><b>10</b> Correlations</a>
<ul>
<li class="chapter" data-level="10.1" data-path="correlations.html"><a href="correlations.html#plotting-correlations"><i class="fa fa-check"></i><b>10.1</b> Plotting correlations</a></li>
<li class="chapter" data-level="10.2" data-path="correlations.html"><a href="correlations.html#computing-correlations"><i class="fa fa-check"></i><b>10.2</b> Computing correlations</a></li>
<li class="chapter" data-level="10.3" data-path="correlations.html"><a href="correlations.html#significance"><i class="fa fa-check"></i><b>10.3</b> Significance: A way to help you judge your findings</a></li>
<li class="chapter" data-level="10.4" data-path="correlations.html"><a href="correlations.html#limitations-of-correlations"><i class="fa fa-check"></i><b>10.4</b> Limitations of correlations</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="correlations.html"><a href="correlations.html#correlations-are-not-causal-relationships"><i class="fa fa-check"></i><b>10.4.1</b> Correlations are not causal relationships</a></li>
<li class="chapter" data-level="10.4.2" data-path="correlations.html"><a href="correlations.html#correlations-can-be-spurious"><i class="fa fa-check"></i><b>10.4.2</b> Correlations can be spurious</a></li>
<li class="chapter" data-level="10.4.3" data-path="correlations.html"><a href="correlations.html#simpsons-paradox"><i class="fa fa-check"></i><b>10.4.3</b> Simpson’s Paradox: When correlations betray you</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="power-analysis.html"><a href="power-analysis.html"><i class="fa fa-check"></i><b>11</b> Power: You either have it or you don’t</a>
<ul>
<li class="chapter" data-level="11.1" data-path="power-analysis.html"><a href="power-analysis.html#ingredients-power-analysis"><i class="fa fa-check"></i><b>11.1</b> Ingredients to achieve the power you deserve</a></li>
<li class="chapter" data-level="11.2" data-path="power-analysis.html"><a href="power-analysis.html#computing-power"><i class="fa fa-check"></i><b>11.2</b> Computing power</a></li>
<li class="chapter" data-level="11.3" data-path="power-analysis.html"><a href="power-analysis.html#plotting-power"><i class="fa fa-check"></i><b>11.3</b> Plotting power</a></li>
<li class="chapter" data-level="11.4" data-path="power-analysis.html"><a href="power-analysis.html#concluding-remarks-about-power-analysis"><i class="fa fa-check"></i><b>11.4</b> Concluding remarks about power analysis</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="comparing-groups.html"><a href="comparing-groups.html"><i class="fa fa-check"></i><b>12</b> Comparing groups</a>
<ul>
<li class="chapter" data-level="12.1" data-path="comparing-groups.html"><a href="comparing-groups.html#comparability-apples-vs-oranges"><i class="fa fa-check"></i><b>12.1</b> Comparability: Apples vs Oranges</a></li>
<li class="chapter" data-level="12.2" data-path="comparing-groups.html"><a href="comparing-groups.html#comparing-two-groups"><i class="fa fa-check"></i><b>12.2</b> Comparing two groups</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="comparing-groups.html"><a href="comparing-groups.html#two-unpaired-groups"><i class="fa fa-check"></i><b>12.2.1</b> Two unpaired groups</a></li>
<li class="chapter" data-level="12.2.2" data-path="comparing-groups.html"><a href="comparing-groups.html#two-paired-groups"><i class="fa fa-check"></i><b>12.2.2</b> Two paired groups</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="comparing-groups.html"><a href="comparing-groups.html#comparing-more-than-two-groups"><i class="fa fa-check"></i><b>12.3</b> Comparing more than two groups</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="comparing-groups.html"><a href="comparing-groups.html#multiple-unpaired-groups"><i class="fa fa-check"></i><b>12.3.1</b> Multiple unpaired groups</a></li>
<li class="chapter" data-level="12.3.2" data-path="comparing-groups.html"><a href="comparing-groups.html#multiple-paired-groups"><i class="fa fa-check"></i><b>12.3.2</b> Multiple paired groups</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="comparing-groups.html"><a href="comparing-groups.html#chi-squared-test"><i class="fa fa-check"></i><b>12.4</b> Comparing groups based on factors: Contingency tables</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="comparing-groups.html"><a href="comparing-groups.html#unpaired-groups-categorical-variables"><i class="fa fa-check"></i><b>12.4.1</b> Unpaired groups of categorical variables</a></li>
<li class="chapter" data-level="12.4.2" data-path="comparing-groups.html"><a href="comparing-groups.html#paired-groups-categorical-variables"><i class="fa fa-check"></i><b>12.4.2</b> Paired groups of categorical variables</a></li>
<li class="chapter" data-level="12.4.3" data-path="comparing-groups.html"><a href="comparing-groups.html#a-final-remark-about-comparing-groups-based-on-categorical-data"><i class="fa fa-check"></i><b>12.4.3</b> A final remark about comparing groups based on categorical data</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="comparing-groups.html"><a href="comparing-groups.html#reviewing-group-comparisons"><i class="fa fa-check"></i><b>12.5</b> Reviewing group comparisons</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>13</b> Regression: Creating models to predict future observations</a>
<ul>
<li class="chapter" data-level="13.1" data-path="regression.html"><a href="regression.html#single-linear-regression"><i class="fa fa-check"></i><b>13.1</b> Single linear regression</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="regression.html"><a href="regression.html#fitting-a-regression-model-by-hand"><i class="fa fa-check"></i><b>13.1.1</b> Fitting a regression model by hand, i.e. trial and error</a></li>
<li class="chapter" data-level="13.1.2" data-path="regression.html"><a href="regression.html#fitting-a-regression-model-computationally"><i class="fa fa-check"></i><b>13.1.2</b> Fitting a regression model computationally</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="regression.html"><a href="regression.html#multiple-regression"><i class="fa fa-check"></i><b>13.2</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="regression.html"><a href="regression.html#outliers-in-multiple-regressions"><i class="fa fa-check"></i><b>13.2.1</b> Outliers in multiple regressions</a></li>
<li class="chapter" data-level="13.2.2" data-path="regression.html"><a href="regression.html#standardised-beta-beta-vs.-unstandardised-beta-b"><i class="fa fa-check"></i><b>13.2.2</b> Standardised beta (<span class="math inline">\(\beta\)</span>) vs. unstandardised beta (<span class="math inline">\(B\)</span>)</a></li>
<li class="chapter" data-level="13.2.3" data-path="regression.html"><a href="regression.html#multicollinearity-the-dilemma-of-highly-correlated-independent-variables"><i class="fa fa-check"></i><b>13.2.3</b> Multicollinearity: The dilemma of highly correlated independent variables</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="regression.html"><a href="regression.html#hierarchical-regression"><i class="fa fa-check"></i><b>13.3</b> Hierarchical regression</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="regression.html"><a href="regression.html#regressions-with-control-variables"><i class="fa fa-check"></i><b>13.3.1</b> Regressions with control variables</a></li>
<li class="chapter" data-level="13.3.2" data-path="regression.html"><a href="regression.html#moderated-regression"><i class="fa fa-check"></i><b>13.3.2</b> Moderated regression</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="regression.html"><a href="regression.html#other-regression-models-alternatives-to-ols"><i class="fa fa-check"></i><b>13.4</b> Other regression models: Alternatives to OLS</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="mixed-methods-research.html"><a href="mixed-methods-research.html"><i class="fa fa-check"></i><b>14</b> Mixed-methods research: Analysing qualitative in R</a>
<ul>
<li class="chapter" data-level="14.1" data-path="mixed-methods-research.html"><a href="mixed-methods-research.html#tidy-process-for-textual-data"><i class="fa fa-check"></i><b>14.1</b> The tidy process of working with textual data</a></li>
<li class="chapter" data-level="14.2" data-path="mixed-methods-research.html"><a href="mixed-methods-research.html#stop-words-removing-noise-in-the-data"><i class="fa fa-check"></i><b>14.2</b> Stop words: Removing noise in the data</a></li>
<li class="chapter" data-level="14.3" data-path="mixed-methods-research.html"><a href="mixed-methods-research.html#n-grams"><i class="fa fa-check"></i><b>14.3</b> N-grams: Exploring correlations of words</a></li>
<li class="chapter" data-level="14.4" data-path="mixed-methods-research.html"><a href="mixed-methods-research.html#exploring-more-mixed-methods-research-approaches-in-r"><i class="fa fa-check"></i><b>14.4</b> Exploring more mixed-methods research approaches in R</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="next-steps.html"><a href="next-steps.html"><i class="fa fa-check"></i><b>15</b> Where to go from here: The next steps in your R journey</a>
<ul>
<li class="chapter" data-level="15.1" data-path="next-steps.html"><a href="next-steps.html#github-a-gateway-to-even-more-ingenious-r-packages"><i class="fa fa-check"></i><b>15.1</b> GitHub: A Gateway to even more ingenious R packages</a></li>
<li class="chapter" data-level="15.2" data-path="next-steps.html"><a href="next-steps.html#books-to-read-and-expand-your-knowledge"><i class="fa fa-check"></i><b>15.2</b> Books to read and expand your knowledge</a></li>
<li class="chapter" data-level="15.3" data-path="next-steps.html"><a href="next-steps.html#engage-in-regular-online-readings-about-r"><i class="fa fa-check"></i><b>15.3</b> Engage in regular online readings about R</a></li>
<li class="chapter" data-level="15.4" data-path="next-steps.html"><a href="next-steps.html#join-the-twitter-community-and-hone-your-skills"><i class="fa fa-check"></i><b>15.4</b> Join the Twitter community and hone your skills</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="case-studies-in-depth-analysis.html"><a href="case-studies-in-depth-analysis.html"><i class="fa fa-check"></i><b>16</b> Case studies: In-depth analysis</a>
<ul>
<li class="chapter" data-level="16.1" data-path="case-studies-in-depth-analysis.html"><a href="case-studies-in-depth-analysis.html#bootstrapped-regression"><i class="fa fa-check"></i><b>16.1</b> Bootstrapped regression with multi-level control variable and moderation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="epilogue.html"><a href="epilogue.html"><i class="fa fa-check"></i>Epilogue</a></li>
<li class="chapter" data-level="17" data-path="case-studies-in-depth-analysis-1.html"><a href="case-studies-in-depth-analysis-1.html"><i class="fa fa-check"></i><b>17</b> Case studies: In-depth analysis</a>
<ul>
<li class="chapter" data-level="17.1" data-path="case-studies-in-depth-analysis-1.html"><a href="case-studies-in-depth-analysis-1.html#case-study-bootstrapped-regression"><i class="fa fa-check"></i><b>17.1</b> Bootstrapped regression with multi-level control variable and moderation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix</a>
<ul>
<li class="chapter" data-level="17.2" data-path="appendix.html"><a href="appendix.html#comparing-two-unpaired-groups"><i class="fa fa-check"></i><b>17.2</b> Comparing two unpaired groups</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="exercises-solutions.html"><a href="exercises-solutions.html"><i class="fa fa-check"></i><b>18</b> Exercises: Solutions</a>
<ul>
<li class="chapter" data-level="18.1" data-path="exercises-solutions.html"><a href="exercises-solutions.html#exercises-solutions-5"><i class="fa fa-check"></i><b>18.1</b> Solutions for 5.6</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://twitter.com/daniel_dauber" target="blank">Find me on twitter!</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for Non-Programmers: A Guide for Social Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="correlations" class="section level1" number="10">
<h1><span class="header-section-number">10</span> Correlations</h1>
<p>Sometimes counting and measuring means, medians, and standard deviations is not enough because they are all based on a single variable. Instead, we might have questions related to the relationship of two or more variables. In this section, we will explore how correlations can (and kind of cannot - see Chapter <a href="correlations.html#simpsons-paradox">10.4.3</a>) provide insights into the following questions:</p>
<ul>
<li><p>Do movie viewers agree with critics regarding the rating of movies?</p></li>
<li><p>Do popular movies receive more votes from users than less popular movies?</p></li>
<li><p>Do movies with more votes also make more money?</p></li>
</ul>
<p>There are many different ways to compute the correlation, and it partially depends on the type of data you want to relate to each other. The ‘Pearson’s correlation’ is by far the most frequently used correlation technique for normally distributed data. On the other hand, if data is not normally distributed, we can opt for the ‘Spearman’s rank’ correlation. One could argue that the relationship between these two correlations is like the mean (Pearson) to the median (Spearman). Both approaches require numeric values to be computed correctly. If our data is ordinal, or worse dichotomous (like a logical variable), we have to choose different options.</p>
<table>
<caption><span id="tab:different-correlations">Table 10.1: </span> Different ways of computing correlations</caption>
<colgroup>
<col width="19%" />
<col width="80%" />
</colgroup>
<thead>
<tr class="header">
<th>Correlation</th>
<th>Used</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Pearson</em></td>
<td>Requires variables to be parametric and therefore numeric</td>
</tr>
<tr class="even">
<td><em>Spearman</em></td>
<td>Used when data is non-parametric and requires numeric variables</td>
</tr>
<tr class="odd">
<td><em>Polychoric</em></td>
<td>Used when investigating two ordinal variables</td>
</tr>
<tr class="even">
<td><em>Tetrachoric</em></td>
<td>Used when both variables are dichotomous, e.g. ‘yes/no,’ ‘True/False.’</td>
</tr>
<tr class="odd">
<td><em>Rank-biserial</em></td>
<td>Used when one variable is dichotomous and the other variable is ordinal</td>
</tr>
</tbody>
</table>
<p>There are many more variations of correlations, which you can explore on the <a href="https://easystats.github.io/correlation/articles/types.html" target="blank" title="website of the package">package’s website</a> we will use in this chapter: <code>correlation</code>. However, we will primarily focus on Pearson, Spearman and the Chi-Squared test because they are the most commonly used correlation types in academic publications to understand the relationship between two variables. In addition, we also look at ‘partial correlations,’ which allow us to introduce a third variable into this mix.</p>
<div id="plotting-correlations" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Plotting correlations</h2>
<p>Since correlations only show the relationship between two variables, we can easily put one variable on the x-axis and one on the y-axis, creating a so-called ‘scatterplot.’ We used the functions to plot scatterplots before, i.e. <code>geom_point()</code> and <code>geom_jitter</code>. Let’s try to answer our first research question, i.e. whether regular movie viewers and critics (people who review movies as a profession) rate the top 250 in the same way. One assumption could be that it does not matter whether you are a regular movie viewer or someone who does it professionally. After all, we are just human beings. A counter thesis could be that critics have a different perspective on movies and might use other evaluation criteria. Either way, we first need to identify the two variables of interest:</p>
<ul>
<li><p><code>imdb_rating</code> is based on IMDb users</p></li>
<li><p><code>metascore</code> is based on movie critics</p></li>
</ul>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="correlations.html#cb119-1" aria-hidden="true" tabindex="-1"></a>imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb119-2"><a href="correlations.html#cb119-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(metascore)) <span class="sc">%&gt;%</span></span>
<span id="cb119-3"><a href="correlations.html#cb119-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(imdb_rating, metascore)) <span class="sc">+</span></span>
<span id="cb119-4"><a href="correlations.html#cb119-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb119-5"><a href="correlations.html#cb119-5" aria-hidden="true" tabindex="-1"></a>  see<span class="sc">::</span><span class="fu">theme_modern</span>()</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Correlation%20between%20imdb_rating%20and%20metascore-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The results from our scatterplot are, well, somewhat random. We can see that some movies receive high <code>imdb_rating</code>s as well as high <code>metascore</code>s. However, some movies receive high <code>imdb_rating</code>s but low <code>metascore</code>s. Overall, the points look like they are randomly scattered all over our canvas. The only visible pattern we can notice is that there are more movies at the lower end of the rating system relative to all the films in the top 250. In fact, there are only two movies that received an IMDb rating of over 9. Be aware, <code>geom_jitter()</code> makes it look like there were more than 9!).</p>
<p>Since correlations only explain linear relationships, a perfect correlation would be represented by a straight line. Consider the following examples of correlations:</p>
<p><img src="r_for_non_programmers_files/figure-html/Examples%20of%20correlations-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>A correlation can be either positive or negative, and its value (i.e. <code>r</code> in case of the Pearson correlation) can range from <code>-1</code> to <code>1</code>:</p>
<ul>
<li><p><code>-1</code> defines a perfectly negative correlation,</p></li>
<li><p><code>0</code> defines no correlation (completely random), and</p></li>
<li><p><code>1</code> defines a perfectly positive correlation.</p></li>
</ul>
<p>In other words, the further the score is away from zero, the stronger is the relationship between variables. We also have benchmarks that we can use to assess the strength of a relationship, for example, the one by <span class="citation"><a href="#ref-cohen1988statistical" role="doc-biblioref">J. Cohen</a> (<a href="#ref-cohen1988statistical" role="doc-biblioref">1988</a>)</span>. The strength of the relationship is also called ‘effect size.’ Table <a href="correlations.html#tab:effect-size-cohen">10.2</a> shows the relevant benchmarks. Note that effect sizes are always provided as absolute figures. Therefore, -0.4 would also count as a moderate relationship.</p>
<table>
<caption><span id="tab:effect-size-cohen">Table 10.2: </span> Assessing effect size of relationships according to Cohen (1988)</caption>
<thead>
<tr class="header">
<th>effect size</th>
<th>interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>r &lt; 0.1</td>
<td>very small</td>
</tr>
<tr class="even">
<td>0.1 <span class="math inline">\(\leq\)</span> r &lt; 0.3</td>
<td>small</td>
</tr>
<tr class="odd">
<td>0.3 <span class="math inline">\(\leq\)</span> r &lt; 0.5</td>
<td>moderate</td>
</tr>
<tr class="even">
<td>r <span class="math inline">\(\geq\)</span> 0.5</td>
<td>large</td>
</tr>
</tbody>
</table>
</div>
<div id="computing-correlations" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> Computing correlations</h2>
<p>If we compare the plot from our data with the sample plots, we will conclude that the relationship is weak, and therefore the <code>r</code> must be close to zero. We can test this with the Pearson correlation using the function <code>correlation()</code> from the <code>correlation</code> package. By default, it will perform a Pearson correlation, which is only applicable for parametric data. If our data violates the assumptions for parametric tests, we can use Spearman’s correlation methods instead. For the rest of the chapter, we assume that our data is parametric.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="correlations.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(correlation)</span>
<span id="cb120-2"><a href="correlations.html#cb120-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-3"><a href="correlations.html#cb120-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Pearson correlation</span></span>
<span id="cb120-4"><a href="correlations.html#cb120-4" aria-hidden="true" tabindex="-1"></a>imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb120-5"><a href="correlations.html#cb120-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(imdb_rating, metascore) <span class="sc">%&gt;%</span></span>
<span id="cb120-6"><a href="correlations.html#cb120-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlation</span>()</span>
<span id="cb120-7"><a href="correlations.html#cb120-7" aria-hidden="true" tabindex="-1"></a><span class="do">## # Correlation Matrix (pearson-method)</span></span>
<span id="cb120-8"><a href="correlations.html#cb120-8" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb120-9"><a href="correlations.html#cb120-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Parameter1  | Parameter2 |    r |        95% CI | t(214) |     p</span></span>
<span id="cb120-10"><a href="correlations.html#cb120-10" aria-hidden="true" tabindex="-1"></a><span class="do">## ----------------------------------------------------------------</span></span>
<span id="cb120-11"><a href="correlations.html#cb120-11" aria-hidden="true" tabindex="-1"></a><span class="do">## imdb_rating |  metascore | 0.08 | [-0.06, 0.21] |   1.11 | 0.270</span></span>
<span id="cb120-12"><a href="correlations.html#cb120-12" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb120-13"><a href="correlations.html#cb120-13" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value adjustment method: Holm (1979)</span></span>
<span id="cb120-14"><a href="correlations.html#cb120-14" aria-hidden="true" tabindex="-1"></a><span class="do">## Observations: 216</span></span>
<span id="cb120-15"><a href="correlations.html#cb120-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Spearman correlation</span></span>
<span id="cb120-16"><a href="correlations.html#cb120-16" aria-hidden="true" tabindex="-1"></a>imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb120-17"><a href="correlations.html#cb120-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(imdb_rating, metascore) <span class="sc">%&gt;%</span></span>
<span id="cb120-18"><a href="correlations.html#cb120-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlation</span>(<span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span>
<span id="cb120-19"><a href="correlations.html#cb120-19" aria-hidden="true" tabindex="-1"></a><span class="do">## # Correlation Matrix (spearman-method)</span></span>
<span id="cb120-20"><a href="correlations.html#cb120-20" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb120-21"><a href="correlations.html#cb120-21" aria-hidden="true" tabindex="-1"></a><span class="do">## Parameter1  | Parameter2 |  rho |        95% CI |        S |     p</span></span>
<span id="cb120-22"><a href="correlations.html#cb120-22" aria-hidden="true" tabindex="-1"></a><span class="do">## ------------------------------------------------------------------</span></span>
<span id="cb120-23"><a href="correlations.html#cb120-23" aria-hidden="true" tabindex="-1"></a><span class="do">## imdb_rating |  metascore | 0.06 | [-0.08, 0.19] | 1.58e+06 | 0.406</span></span>
<span id="cb120-24"><a href="correlations.html#cb120-24" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb120-25"><a href="correlations.html#cb120-25" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value adjustment method: Holm (1979)</span></span>
<span id="cb120-26"><a href="correlations.html#cb120-26" aria-hidden="true" tabindex="-1"></a><span class="do">## Observations: 216</span></span></code></pre></div>
<p>Indeed, our analysis reveals that the effect size is very small (r = 0.08 &lt; 0.1). Therefore, critics appear to rate movies differently than regular movie viewers, irrespective of which method we use. This mistmatch of ratings triggers an interesting follow-up question: Which movie is the most controversial, i.e. where is the difference between <code>imdb_rating</code> and <code>metascore</code> the highest?</p>
<p>We can answer this question with the tools we already know. We create a new variable to subtract the <code>metascore</code> from the <code>imdb_rating</code> and plot it. We have to make sure both scales are the same length. The variable <code>imdb_rating</code> ranges from 0-10, but the <code>metascore</code> ranges from 0-100. I used the percentile score instead by dividing the scores by 10 and 100, respectively. Since plotting 250 movies would have been too much and would also not help us find the answer to our question, I chose arbitrary values to pick only those movies with the highest differences in scores. Feel free to adjust the filter to your liking to see more or fewer movies.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="correlations.html#cb121-1" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">&lt;-</span></span>
<span id="cb121-2"><a href="correlations.html#cb121-2" aria-hidden="true" tabindex="-1"></a>  imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb121-3"><a href="correlations.html#cb121-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">r_diff =</span> imdb_rating <span class="sc">/</span> <span class="dv">10</span> <span class="sc">-</span> metascore <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb121-4"><a href="correlations.html#cb121-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(r_diff) <span class="sc">&amp;</span> r_diff <span class="sc">&gt;=</span> <span class="fl">0.25</span> <span class="sc">|</span> r_diff <span class="sc">&lt;=</span> <span class="sc">-</span><span class="fl">0.165</span>)</span>
<span id="cb121-5"><a href="correlations.html#cb121-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-6"><a href="correlations.html#cb121-6" aria-hidden="true" tabindex="-1"></a>plot <span class="sc">%&gt;%</span></span>
<span id="cb121-7"><a href="correlations.html#cb121-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(title, r_diff), <span class="at">y =</span> r_diff, <span class="at">label =</span> title)) <span class="sc">+</span></span>
<span id="cb121-8"><a href="correlations.html#cb121-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="fu">ifelse</span>(r_diff <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">&quot;Viewers&quot;</span>, <span class="st">&quot;Critics&quot;</span>))) <span class="sc">+</span></span>
<span id="cb121-9"><a href="correlations.html#cb121-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-10"><a href="correlations.html#cb121-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">x =</span> title, <span class="at">y =</span> <span class="dv">0</span>,</span>
<span id="cb121-11"><a href="correlations.html#cb121-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">label =</span> title),</span>
<span id="cb121-12"><a href="correlations.html#cb121-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="fl">2.5</span>,</span>
<span id="cb121-13"><a href="correlations.html#cb121-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-14"><a href="correlations.html#cb121-14" aria-hidden="true" tabindex="-1"></a>            <span class="co"># to adjust the labels of the plot</span></span>
<span id="cb121-15"><a href="correlations.html#cb121-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="fu">ifelse</span>(plot<span class="sc">$</span>r_diff <span class="sc">&gt;=</span> <span class="dv">0</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>),</span>
<span id="cb121-16"><a href="correlations.html#cb121-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="fu">ifelse</span>(plot<span class="sc">$</span>r_diff <span class="sc">&gt;=</span> <span class="dv">0</span>, <span class="fl">1.05</span>, <span class="sc">-</span><span class="fl">0.05</span>)</span>
<span id="cb121-17"><a href="correlations.html#cb121-17" aria-hidden="true" tabindex="-1"></a>            ) <span class="sc">+</span></span>
<span id="cb121-18"><a href="correlations.html#cb121-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb121-19"><a href="correlations.html#cb121-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-20"><a href="correlations.html#cb121-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Cleaning up the plot to make it look more readable and colourful</span></span>
<span id="cb121-21"><a href="correlations.html#cb121-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#FFCE7D&quot;</span>, <span class="st">&quot;#7DC0FF&quot;</span>)) <span class="sc">+</span></span>
<span id="cb121-22"><a href="correlations.html#cb121-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb121-23"><a href="correlations.html#cb121-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Biggest%20discrepancy%20in%20movie%20ratings-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Another question we posed at the beginning was: Do higher-ranked movies receive more votes from users than lower-ranked ones? Our intuition might say ‘yes.’ If movies are ranked higher, they are likely seen by more people, which makes them more popular. Consequently, the more people have seen a movie, the more likely they might vote for this movie. For lower ranked movies, the opposite should be true. Let’s create another scatterplot to find out.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="correlations.html#cb122-1" aria-hidden="true" tabindex="-1"></a>imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb122-2"><a href="correlations.html#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> imdb_rating, <span class="at">y =</span> votes)) <span class="sc">+</span></span>
<span id="cb122-3"><a href="correlations.html#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb122-4"><a href="correlations.html#cb122-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_number</span>(<span class="at">big.mark =</span> <span class="st">&quot;,&quot;</span>))</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Ratings%20vs%20votes-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The last line of code helps to make the labels on the y axis more readable. The numbers are in the millions, and it helps to have the indicators present using <code>label_number()</code> from the <code>scales</code> package.</p>
<p>The scatterplot shows a somewhat positive trend. Often, it can be tough to see the trend. To improve our plot, we can use the function <code>geom_smooth()</code>, which can help us draw a straight line that best fits our data points. We need to set the <code>method</code> for drawing the line to <code>lm</code>, which stands for ‘linear model.’ Remember, correlations assume a linear relationship between two variables.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="correlations.html#cb123-1" aria-hidden="true" tabindex="-1"></a>imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb123-2"><a href="correlations.html#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> imdb_rating, <span class="at">y =</span> votes)) <span class="sc">+</span></span>
<span id="cb123-3"><a href="correlations.html#cb123-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb123-4"><a href="correlations.html#cb123-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb123-5"><a href="correlations.html#cb123-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> y <span class="sc">~</span> x,</span>
<span id="cb123-6"><a href="correlations.html#cb123-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb123-7"><a href="correlations.html#cb123-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Ratings%20vs%20votes%20plus%20regression%20line-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Another problem we face with this plot (and correlations) are extreme values, i.e. outliers. We already know that outliers tend to cause trouble for our analysis (see Chapter <a href="sources-of-bias.html#dealing-with-outliers">9.5</a>, and in correlations, they can affect the strength of relationships. However, the differences are very significant if we compute the Pearson correlation with and without outliers. Be aware that since we work with two variables simultaneously, we should consider outliers in both. The function <code>filter()</code> will have to include four conditions.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="correlations.html#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The correlation with outliers</span></span>
<span id="cb124-2"><a href="correlations.html#cb124-2" aria-hidden="true" tabindex="-1"></a>imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb124-3"><a href="correlations.html#cb124-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(imdb_rating, votes) <span class="sc">%&gt;%</span></span>
<span id="cb124-4"><a href="correlations.html#cb124-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlation</span>()</span>
<span id="cb124-5"><a href="correlations.html#cb124-5" aria-hidden="true" tabindex="-1"></a><span class="do">## # Correlation Matrix (pearson-method)</span></span>
<span id="cb124-6"><a href="correlations.html#cb124-6" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb124-7"><a href="correlations.html#cb124-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Parameter1  | Parameter2 |    r |       95% CI | t(248) |         p</span></span>
<span id="cb124-8"><a href="correlations.html#cb124-8" aria-hidden="true" tabindex="-1"></a><span class="do">## -------------------------------------------------------------------</span></span>
<span id="cb124-9"><a href="correlations.html#cb124-9" aria-hidden="true" tabindex="-1"></a><span class="do">## imdb_rating |      votes | 0.59 | [0.51, 0.67] |  11.57 | &lt; .001***</span></span>
<span id="cb124-10"><a href="correlations.html#cb124-10" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb124-11"><a href="correlations.html#cb124-11" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value adjustment method: Holm (1979)</span></span>
<span id="cb124-12"><a href="correlations.html#cb124-12" aria-hidden="true" tabindex="-1"></a><span class="do">## Observations: 250</span></span>
<span id="cb124-13"><a href="correlations.html#cb124-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute quartiles</span></span>
<span id="cb124-14"><a href="correlations.html#cb124-14" aria-hidden="true" tabindex="-1"></a>votes_quantiles <span class="ot">&lt;-</span> <span class="fu">quantile</span>(imdb_top_250<span class="sc">$</span>votes)</span>
<span id="cb124-15"><a href="correlations.html#cb124-15" aria-hidden="true" tabindex="-1"></a>rating_quantiles <span class="ot">&lt;-</span> <span class="fu">quantile</span>(imdb_top_250<span class="sc">$</span>imdb_rating)</span>
<span id="cb124-16"><a href="correlations.html#cb124-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-17"><a href="correlations.html#cb124-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Define outliers</span></span>
<span id="cb124-18"><a href="correlations.html#cb124-18" aria-hidden="true" tabindex="-1"></a>votes_out_upper <span class="ot">&lt;-</span> votes_quantiles[<span class="dv">4</span>] <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> <span class="fu">IQR</span>(imdb_top_250<span class="sc">$</span>votes)</span>
<span id="cb124-19"><a href="correlations.html#cb124-19" aria-hidden="true" tabindex="-1"></a>votes_out_lower <span class="ot">&lt;-</span> votes_quantiles[<span class="dv">2</span>] <span class="sc">-</span> <span class="fl">1.5</span> <span class="sc">*</span> <span class="fu">IQR</span>(imdb_top_250<span class="sc">$</span>votes)</span>
<span id="cb124-20"><a href="correlations.html#cb124-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-21"><a href="correlations.html#cb124-21" aria-hidden="true" tabindex="-1"></a>rating_out_upper <span class="ot">&lt;-</span> rating_quantiles[<span class="dv">4</span>] <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> <span class="fu">IQR</span>(imdb_top_250<span class="sc">$</span>imdb_rating)</span>
<span id="cb124-22"><a href="correlations.html#cb124-22" aria-hidden="true" tabindex="-1"></a>rating_out_lower <span class="ot">&lt;-</span> rating_quantiles[<span class="dv">2</span>] <span class="sc">-</span> <span class="fl">1.5</span> <span class="sc">*</span> <span class="fu">IQR</span>(imdb_top_250<span class="sc">$</span>imdb_rating)</span>
<span id="cb124-23"><a href="correlations.html#cb124-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-24"><a href="correlations.html#cb124-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove outliers</span></span>
<span id="cb124-25"><a href="correlations.html#cb124-25" aria-hidden="true" tabindex="-1"></a>movies_no_out <span class="ot">&lt;-</span></span>
<span id="cb124-26"><a href="correlations.html#cb124-26" aria-hidden="true" tabindex="-1"></a>  imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb124-27"><a href="correlations.html#cb124-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(votes <span class="sc">&lt;=</span> votes_out_upper <span class="sc">&amp;</span></span>
<span id="cb124-28"><a href="correlations.html#cb124-28" aria-hidden="true" tabindex="-1"></a>           votes <span class="sc">&gt;=</span> votes_out_lower <span class="sc">&amp;</span></span>
<span id="cb124-29"><a href="correlations.html#cb124-29" aria-hidden="true" tabindex="-1"></a>           imdb_rating <span class="sc">&lt;=</span> rating_out_upper <span class="sc">&amp;</span></span>
<span id="cb124-30"><a href="correlations.html#cb124-30" aria-hidden="true" tabindex="-1"></a>           imdb_rating <span class="sc">&gt;=</span> rating_out_lower)</span>
<span id="cb124-31"><a href="correlations.html#cb124-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-32"><a href="correlations.html#cb124-32" aria-hidden="true" tabindex="-1"></a><span class="co"># The correlation without outliers (based on 1.5 * IQR)</span></span>
<span id="cb124-33"><a href="correlations.html#cb124-33" aria-hidden="true" tabindex="-1"></a>movies_no_out <span class="sc">%&gt;%</span></span>
<span id="cb124-34"><a href="correlations.html#cb124-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(votes <span class="sc">&lt;=</span> votes_out_upper <span class="sc">&amp;</span></span>
<span id="cb124-35"><a href="correlations.html#cb124-35" aria-hidden="true" tabindex="-1"></a>           votes <span class="sc">&gt;=</span> votes_out_lower <span class="sc">&amp;</span></span>
<span id="cb124-36"><a href="correlations.html#cb124-36" aria-hidden="true" tabindex="-1"></a>           imdb_rating <span class="sc">&lt;=</span> rating_out_upper <span class="sc">&amp;</span></span>
<span id="cb124-37"><a href="correlations.html#cb124-37" aria-hidden="true" tabindex="-1"></a>           imdb_rating <span class="sc">&gt;=</span> rating_out_lower) <span class="sc">%&gt;%</span></span>
<span id="cb124-38"><a href="correlations.html#cb124-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(imdb_rating, votes) <span class="sc">%&gt;%</span></span>
<span id="cb124-39"><a href="correlations.html#cb124-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlation</span>()</span>
<span id="cb124-40"><a href="correlations.html#cb124-40" aria-hidden="true" tabindex="-1"></a><span class="do">## # Correlation Matrix (pearson-method)</span></span>
<span id="cb124-41"><a href="correlations.html#cb124-41" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb124-42"><a href="correlations.html#cb124-42" aria-hidden="true" tabindex="-1"></a><span class="do">## Parameter1  | Parameter2 |    r |       95% CI | t(238) |         p</span></span>
<span id="cb124-43"><a href="correlations.html#cb124-43" aria-hidden="true" tabindex="-1"></a><span class="do">## -------------------------------------------------------------------</span></span>
<span id="cb124-44"><a href="correlations.html#cb124-44" aria-hidden="true" tabindex="-1"></a><span class="do">## imdb_rating |      votes | 0.43 | [0.32, 0.53] |   7.41 | &lt; .001***</span></span>
<span id="cb124-45"><a href="correlations.html#cb124-45" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb124-46"><a href="correlations.html#cb124-46" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value adjustment method: Holm (1979)</span></span>
<span id="cb124-47"><a href="correlations.html#cb124-47" aria-hidden="true" tabindex="-1"></a><span class="do">## Observations: 240</span></span></code></pre></div>
<p>While both correlations are highly significant (p &lt; 0.01), the drop in <code>r</code> from 0.59 to 0.43 is substantial. When we plot the data again, we can see that the dots are fairly randomly distributed across the plotting area. Thanks to <code>geom_smooth</code> we get an idea of a slight positive relationship between these two variables.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="correlations.html#cb125-1" aria-hidden="true" tabindex="-1"></a>movies_no_out <span class="sc">%&gt;%</span></span>
<span id="cb125-2"><a href="correlations.html#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> imdb_rating, <span class="at">y =</span> votes)) <span class="sc">+</span></span>
<span id="cb125-3"><a href="correlations.html#cb125-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb125-4"><a href="correlations.html#cb125-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb125-5"><a href="correlations.html#cb125-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> y <span class="sc">~</span> x,</span>
<span id="cb125-6"><a href="correlations.html#cb125-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb125-7"><a href="correlations.html#cb125-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Scatterplot%20without%20outliers-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>In conclusion, while there is some relationship between the rating and the number of votes, it is by far not as strong as we might have thought, especially after removing outliers, which had a considerable effect on the effect size.</p>
</div>
<div id="significance" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> Significance: A way to help you judge your findings</h2>
<p>One of the most common pitfalls of novice statisticians is the interpretation of what counts as significant and not significant. Most basic tests offer a ‘p value,’ which stands for ‘probability value.’ The <code>p</code>-value can range from 1 (for 100%) to 0 (for 0%) and implies:</p>
<ul>
<li><p><span class="math inline">\(p = 1\)</span>, there is a 100% chance that the result is a pure coincidence</p></li>
<li><p><span class="math inline">\(p = 0\)</span>, there is a 0% chance that the result is a pure coincidence, i.e. we can be certain this is not just luck.</p></li>
</ul>
<p>Technically, we would not find that <code>p</code> is ever truly zero and instead denote very small <code>p</code>-values with <code>p &lt; 0.01</code> or even <code>p &lt; 0.001</code>.</p>
<p>There are also commonly considered thresholds for the <code>p</code>-value:</p>
<ul>
<li><p><span class="math inline">\(p &gt; 0.05\)</span>, the result is not significant. There is a chance of 5% that our finding is a pure coincidence.</p></li>
<li><p>p <span class="math inline">\(\leq 0.05\)</span> , the result is significant.</p></li>
<li><p>p <span class="math inline">\(\leq 0.01\)</span>, the result is highly significant.</p></li>
</ul>
<p>We will cover more about the <code>p</code>-value in Chapter <a href="comparing-groups.html#comparing-groups">12</a> and Chapter <a href="regression.html#regression">13</a>. For now, it is important to know that a significant correlation is one that we should look at more closely. Usually, correlations that nor significant suffer from small effect sizes. However, different samples can lead to different effect sizes and different significant levels. Consider the following examples:</p>
<pre><code>## # Correlation Matrix (pearson-method)
## 
## Parameter1 | Parameter2 |    r |        95% CI | t(2) |     p
## -------------------------------------------------------------
## x          |          y | 0.77 | [-0.73, 0.99] | 1.73 | 0.225
## 
## p-value adjustment method: Holm (1979)
## Observations: 4
## # Correlation Matrix (pearson-method)
## 
## Parameter1 | Parameter2 |    r |       95% CI | t(10) |       p
## ---------------------------------------------------------------
## x          |          y | 0.77 | [0.36, 0.93] |  3.87 | 0.003**
## 
## p-value adjustment method: Holm (1979)
## Observations: 12</code></pre>
<p>In both examples <span class="math inline">\(r = 0.77\)</span>, but the sample sizes are different (4 vs 12), and the <code>p</code>-values differ. In the first example, <span class="math inline">\(p = 0.225\)</span>, which means the relationship is not significant, while in the second example, we find that <span class="math inline">\(p &lt; 0.01\)</span> and is therefore highly significant. As a general rule, the bigger the sample, the more likely we find significant results, even though the effect size is small. Therefore, it is crucial to interpret correlations base on at least three factors:</p>
<ul>
<li><p>the <code>p</code>-value, i.e. significance level,</p></li>
<li><p>the <code>r</code>-value, i.e. the effect size, and</p></li>
<li><p>the sample size.</p></li>
</ul>
<p>The interplay of all three can help determine whether a relationship is important. Therefore, when we include correlation tables in publications, we have to provide information about all three indicators.</p>
<p>It is common that we do not only compute correlations for two variables at a time. Instead, we can do this for multiple variables simultaneously.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="correlations.html#cb127-1" aria-hidden="true" tabindex="-1"></a>imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb127-2"><a href="correlations.html#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(imdb_rating, metascore, year, votes, gross_in_m) <span class="sc">%&gt;%</span></span>
<span id="cb127-3"><a href="correlations.html#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlation</span>()</span>
<span id="cb127-4"><a href="correlations.html#cb127-4" aria-hidden="true" tabindex="-1"></a><span class="do">## # Correlation Matrix (pearson-method)</span></span>
<span id="cb127-5"><a href="correlations.html#cb127-5" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb127-6"><a href="correlations.html#cb127-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Parameter1  | Parameter2 |     r |         95% CI |     t |  df |         p</span></span>
<span id="cb127-7"><a href="correlations.html#cb127-7" aria-hidden="true" tabindex="-1"></a><span class="do">## ---------------------------------------------------------------------------</span></span>
<span id="cb127-8"><a href="correlations.html#cb127-8" aria-hidden="true" tabindex="-1"></a><span class="do">## imdb_rating |  metascore |  0.08 | [-0.06,  0.21] |  1.11 | 214 | 0.539    </span></span>
<span id="cb127-9"><a href="correlations.html#cb127-9" aria-hidden="true" tabindex="-1"></a><span class="do">## imdb_rating |       year |  0.03 | [-0.10,  0.15] |  0.42 | 248 | 0.678    </span></span>
<span id="cb127-10"><a href="correlations.html#cb127-10" aria-hidden="true" tabindex="-1"></a><span class="do">## imdb_rating |      votes |  0.59 | [ 0.51,  0.67] | 11.57 | 248 | &lt; .001***</span></span>
<span id="cb127-11"><a href="correlations.html#cb127-11" aria-hidden="true" tabindex="-1"></a><span class="do">## imdb_rating | gross_in_m |  0.21 | [ 0.07,  0.33] |  3.07 | 213 | 0.010**  </span></span>
<span id="cb127-12"><a href="correlations.html#cb127-12" aria-hidden="true" tabindex="-1"></a><span class="do">## metascore   |       year | -0.41 | [-0.52, -0.30] | -6.63 | 214 | &lt; .001***</span></span>
<span id="cb127-13"><a href="correlations.html#cb127-13" aria-hidden="true" tabindex="-1"></a><span class="do">## metascore   |      votes | -0.25 | [-0.37, -0.12] | -3.76 | 214 | 0.001**  </span></span>
<span id="cb127-14"><a href="correlations.html#cb127-14" aria-hidden="true" tabindex="-1"></a><span class="do">## metascore   | gross_in_m | -0.13 | [-0.27,  0.01] | -1.83 | 193 | 0.207    </span></span>
<span id="cb127-15"><a href="correlations.html#cb127-15" aria-hidden="true" tabindex="-1"></a><span class="do">## year        |      votes |  0.37 | [ 0.26,  0.47] |  6.29 | 248 | &lt; .001***</span></span>
<span id="cb127-16"><a href="correlations.html#cb127-16" aria-hidden="true" tabindex="-1"></a><span class="do">## year        | gross_in_m |  0.36 | [ 0.23,  0.47] |  5.58 | 213 | &lt; .001***</span></span>
<span id="cb127-17"><a href="correlations.html#cb127-17" aria-hidden="true" tabindex="-1"></a><span class="do">## votes       | gross_in_m |  0.56 | [ 0.46,  0.64] |  9.79 | 213 | &lt; .001***</span></span>
<span id="cb127-18"><a href="correlations.html#cb127-18" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb127-19"><a href="correlations.html#cb127-19" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value adjustment method: Holm (1979)</span></span>
<span id="cb127-20"><a href="correlations.html#cb127-20" aria-hidden="true" tabindex="-1"></a><span class="do">## Observations: 195-250</span></span></code></pre></div>
<p>If you have seen correlation tables before, you might find that <code>correlation()</code> does not produce the classic table by default. If you want it to look like the tables in publications, which are more compact but offer less information, you can use the function <code>summary()</code>.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="correlations.html#cb128-1" aria-hidden="true" tabindex="-1"></a>imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb128-2"><a href="correlations.html#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(imdb_rating, metascore, year, votes, gross_in_m) <span class="sc">%&gt;%</span></span>
<span id="cb128-3"><a href="correlations.html#cb128-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlation</span>() <span class="sc">%&gt;%</span></span>
<span id="cb128-4"><a href="correlations.html#cb128-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span>
<span id="cb128-5"><a href="correlations.html#cb128-5" aria-hidden="true" tabindex="-1"></a><span class="do">## # Correlation Matrix (pearson-method)</span></span>
<span id="cb128-6"><a href="correlations.html#cb128-6" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb128-7"><a href="correlations.html#cb128-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Parameter   | gross_in_m |   votes |     year | metascore</span></span>
<span id="cb128-8"><a href="correlations.html#cb128-8" aria-hidden="true" tabindex="-1"></a><span class="do">## ---------------------------------------------------------</span></span>
<span id="cb128-9"><a href="correlations.html#cb128-9" aria-hidden="true" tabindex="-1"></a><span class="do">## imdb_rating |     0.21** | 0.59*** |     0.03 |      0.08</span></span>
<span id="cb128-10"><a href="correlations.html#cb128-10" aria-hidden="true" tabindex="-1"></a><span class="do">## metascore   |      -0.13 | -0.25** | -0.41*** |          </span></span>
<span id="cb128-11"><a href="correlations.html#cb128-11" aria-hidden="true" tabindex="-1"></a><span class="do">## year        |    0.36*** | 0.37*** |          |          </span></span>
<span id="cb128-12"><a href="correlations.html#cb128-12" aria-hidden="true" tabindex="-1"></a><span class="do">## votes       |    0.56*** |         |          |          </span></span>
<span id="cb128-13"><a href="correlations.html#cb128-13" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb128-14"><a href="correlations.html#cb128-14" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value adjustment method: Holm (1979)</span></span></code></pre></div>
<p>This table answers our final question, i.e. do movies with more votes earn more money. It appears as if this is true, because <span class="math inline">\(r = 0.56\)</span> and <span class="math inline">\(p &lt; 0.001\)</span>. In the classic correlation table, you often see <code>*</code>. These stand for the different significant levels:</p>
<ul>
<li><p><code>*</code>, i.e. <span class="math inline">\(p &lt; 0.05\)</span></p></li>
<li><p><code>**</code>, i.e. <span class="math inline">\(p &lt; 0.01\)</span></p></li>
<li><p><code>***</code>, i.e. <span class="math inline">\(p &lt; 0.001\)</span> (although you might find some do not use this as a separate level)</p></li>
</ul>
<p>In short, the more <code>*</code> there are attached to each value, the more significant a result. Therefore, we likely find the same relationships in newly collected data if there are many <code>*</code>.</p>
</div>
<div id="limitations-of-correlations" class="section level2" number="10.4">
<h2><span class="header-section-number">10.4</span> Limitations of correlations</h2>
<p>Correlations are helpful, but only to some extend. The three most common limitations you should be aware of are:</p>
<ul>
<li><p>Correlations are not causal relationships</p></li>
<li><p>Correlations can be spurious</p></li>
<li><p>Correlations might only appear in sub-samples of your data</p></li>
</ul>
<div id="correlations-are-not-causal-relationships" class="section level3" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Correlations are not causal relationships</h3>
<p>Correlations do not offer insights into causality, i.e. whether a change in one variable causes change in the other variable. Correlations only provide insights into whether these two variables tend to change when one of them changes. Still, sometimes we can infer such causality by the nature of the variables. For example, in countries with heavy rain, more umbrellas are sold. Buying more umbrellas will not cause more rain, but if there is more rain in a country, we rightly assume a higher demand for umbrellas. If we can theorise the relationship between variables, we would rather opt for a regression model instead of a correlation (see Chapter <a href="regression.html#regression">13</a>.</p>
</div>
<div id="correlations-can-be-spurious" class="section level3" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> Correlations can be spurious</h3>
<p>Just because we find a relationship between two variables does not necessarily mean that they are truly related. Instead, it might be possible that a third variable is the reason for the relationship. We call relationships between variables that are caused by a third variable ‘spurious correlations.’ This third variable can either be part of our dataset or even something we have not measured at all. The latter case would make it impossible to investigate the relationship further. However, we can always test whether some of our variables affect the relationship between the two variables of interest. This can be done by using partial correlations. A partial correlation returns the relationship between two variables minus the relationship two a third variable. Figure <a href="correlations.html#fig:illustration-spurious-correlation">10.1</a> depicts this visually. While <code>a</code> and <code>b</code> appear to be correlated, the correlation might only exist because they correlate with <code>x</code>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:illustration-spurious-correlation"></span>
<div id="htmlwidget-f3d9213e1994eb53b4cc" style="width:672px;height:480px;" class="grViz html-widget"></div>
<script type="application/json" data-for="htmlwidget-f3d9213e1994eb53b4cc">{"x":{"diagram":"\n      digraph boxes_and_circles {\n      graph [layout = circo]\n\n      node [shape = circle,\n            style = filled]\n\n      node [fillcolor = Salmon]\n      x\n\n      node [fillcolor = AliceBlue]\n      a b\n\n      # edges\n      x -> {a b} [arrowsize = 0.5,\n                  dir = both]\n\n      a -> b [style = dashed, arrowsize = 0.5, dir = both,\n              fontsize = 8]\n              }\n      ","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figure 10.1: Illustration of a spurious correlation
</p>
</div>
<p>Let’s consider a practical example. We found that <code>votes</code> and <code>gross_in_m</code> are positively correlated with each other. However, could it be possible that this relationship is affected by the year in which the movies were published? We could assume that later movies received more votes because it has become more of a cultural phenomenon to vote about almost everything online<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="correlations.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation between variables</span></span>
<span id="cb129-2"><a href="correlations.html#cb129-2" aria-hidden="true" tabindex="-1"></a>imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb129-3"><a href="correlations.html#cb129-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(votes, gross_in_m, year) <span class="sc">%&gt;%</span></span>
<span id="cb129-4"><a href="correlations.html#cb129-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlation</span>()</span>
<span id="cb129-5"><a href="correlations.html#cb129-5" aria-hidden="true" tabindex="-1"></a><span class="do">## # Correlation Matrix (pearson-method)</span></span>
<span id="cb129-6"><a href="correlations.html#cb129-6" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb129-7"><a href="correlations.html#cb129-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Parameter1 | Parameter2 |    r |       95% CI |    t |  df |         p</span></span>
<span id="cb129-8"><a href="correlations.html#cb129-8" aria-hidden="true" tabindex="-1"></a><span class="do">## ----------------------------------------------------------------------</span></span>
<span id="cb129-9"><a href="correlations.html#cb129-9" aria-hidden="true" tabindex="-1"></a><span class="do">## votes      | gross_in_m | 0.56 | [0.46, 0.64] | 9.79 | 213 | &lt; .001***</span></span>
<span id="cb129-10"><a href="correlations.html#cb129-10" aria-hidden="true" tabindex="-1"></a><span class="do">## votes      |       year | 0.37 | [0.26, 0.47] | 6.29 | 248 | &lt; .001***</span></span>
<span id="cb129-11"><a href="correlations.html#cb129-11" aria-hidden="true" tabindex="-1"></a><span class="do">## gross_in_m |       year | 0.36 | [0.23, 0.47] | 5.58 | 213 | &lt; .001***</span></span>
<span id="cb129-12"><a href="correlations.html#cb129-12" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb129-13"><a href="correlations.html#cb129-13" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value adjustment method: Holm (1979)</span></span>
<span id="cb129-14"><a href="correlations.html#cb129-14" aria-hidden="true" tabindex="-1"></a><span class="do">## Observations: 215-250</span></span>
<span id="cb129-15"><a href="correlations.html#cb129-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation between variables, considering partial correlations</span></span>
<span id="cb129-16"><a href="correlations.html#cb129-16" aria-hidden="true" tabindex="-1"></a>imdb_top_250 <span class="sc">%&gt;%</span></span>
<span id="cb129-17"><a href="correlations.html#cb129-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(votes, gross_in_m, year) <span class="sc">%&gt;%</span></span>
<span id="cb129-18"><a href="correlations.html#cb129-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlation</span>(<span class="at">partial =</span> <span class="cn">TRUE</span>)</span>
<span id="cb129-19"><a href="correlations.html#cb129-19" aria-hidden="true" tabindex="-1"></a><span class="do">## # Correlation Matrix (pearson-method)</span></span>
<span id="cb129-20"><a href="correlations.html#cb129-20" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb129-21"><a href="correlations.html#cb129-21" aria-hidden="true" tabindex="-1"></a><span class="do">## Parameter1 | Parameter2 |    r |       95% CI | t(213) |         p</span></span>
<span id="cb129-22"><a href="correlations.html#cb129-22" aria-hidden="true" tabindex="-1"></a><span class="do">## ------------------------------------------------------------------</span></span>
<span id="cb129-23"><a href="correlations.html#cb129-23" aria-hidden="true" tabindex="-1"></a><span class="do">## votes      | gross_in_m | 0.48 | [0.37, 0.58] |   7.98 | &lt; .001***</span></span>
<span id="cb129-24"><a href="correlations.html#cb129-24" aria-hidden="true" tabindex="-1"></a><span class="do">## votes      |       year | 0.28 | [0.16, 0.40] |   4.31 | &lt; .001***</span></span>
<span id="cb129-25"><a href="correlations.html#cb129-25" aria-hidden="true" tabindex="-1"></a><span class="do">## gross_in_m |       year | 0.16 | [0.03, 0.29] |   2.43 | 0.016*   </span></span>
<span id="cb129-26"><a href="correlations.html#cb129-26" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb129-27"><a href="correlations.html#cb129-27" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value adjustment method: Holm (1979)</span></span>
<span id="cb129-28"><a href="correlations.html#cb129-28" aria-hidden="true" tabindex="-1"></a><span class="do">## Observations: 215</span></span></code></pre></div>
<p>The first table reveals a strong relationship between the variables of interest, i.e. between <code>votes</code> and <code>gross_in_m</code> with an effect size of <span class="math inline">\(r = 0.56\)</span>. There is also a significant relationship between <code>votes</code> and <code>year</code>, <span class="math inline">\(r = 0.37\)</span> and between <code>gross_in_m</code> and <code>year</code>, <span class="math inline">\(r = 0.36\)</span>. Thus, we should control for <code>year</code> to see how it might affect the relationship between <code>votes</code> and <code>gross_in_m</code>. The second table suggests that <code>year</code> does not much affect the relationship between <code>votes</code> and <code>gross_in_m</code>. However, we notice that the relationship between <code>gross_in_m</code> and <code>year</code> substantially goes down to <span class="math inline">\(r = 0.16\)</span>. It appears as if the <code>year</code> has not managed to impact the relationship between <code>votes</code> and <code>gross_in_m</code> all that much. Therefore, we can be more confident that this relationship is likely not spurious. However, we can never be fully sure because we might not have all data that could explain this correlation.</p>
</div>
<div id="simpsons-paradox" class="section level3" number="10.4.3">
<h3><span class="header-section-number">10.4.3</span> Simpson’s Paradox: When correlations betray you</h3>
<p>The final limitation is so important that it even has its own name: the ‘Simpson’s Paradox.’ Let’s find out what is so paradoxical about some correlations. For this demonstration, we have to make use of a different dataset: <code>simpson</code> of the <code>r4np</code> package. It contains information about changes in student <code>performance</code> and changes in <code>happiness</code>. The dataset includes responses from three different groups: <code>Teachers</code>, <code>Students</code> and <code>Parents</code>.</p>
<p>We would assume that an increase in students’ <code>performance</code> will likely increase the <code>happiness</code> of participants. After all, all three have stakes in students’ <code>performance</code>.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="correlations.html#cb130-1" aria-hidden="true" tabindex="-1"></a>simpson <span class="sc">%&gt;%</span></span>
<span id="cb130-2"><a href="correlations.html#cb130-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(performance, happiness)) <span class="sc">+</span></span>
<span id="cb130-3"><a href="correlations.html#cb130-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb130-4"><a href="correlations.html#cb130-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb130-5"><a href="correlations.html#cb130-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> y <span class="sc">~</span> x,</span>
<span id="cb130-6"><a href="correlations.html#cb130-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb130-7"><a href="correlations.html#cb130-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Simpson%20paradox%20plot%20and%20correlation%20all%201-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="correlations.html#cb131-1" aria-hidden="true" tabindex="-1"></a>simpson <span class="sc">%&gt;%</span></span>
<span id="cb131-2"><a href="correlations.html#cb131-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(performance, happiness) <span class="sc">%&gt;%</span></span>
<span id="cb131-3"><a href="correlations.html#cb131-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlation</span>()</span>
<span id="cb131-4"><a href="correlations.html#cb131-4" aria-hidden="true" tabindex="-1"></a><span class="do">## # Correlation Matrix (pearson-method)</span></span>
<span id="cb131-5"><a href="correlations.html#cb131-5" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb131-6"><a href="correlations.html#cb131-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Parameter1  | Parameter2 |     r |         95% CI | t(298) |         p</span></span>
<span id="cb131-7"><a href="correlations.html#cb131-7" aria-hidden="true" tabindex="-1"></a><span class="do">## ----------------------------------------------------------------------</span></span>
<span id="cb131-8"><a href="correlations.html#cb131-8" aria-hidden="true" tabindex="-1"></a><span class="do">## performance |  happiness | -0.34 | [-0.44, -0.24] |  -6.32 | &lt; .001***</span></span>
<span id="cb131-9"><a href="correlations.html#cb131-9" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb131-10"><a href="correlations.html#cb131-10" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value adjustment method: Holm (1979)</span></span>
<span id="cb131-11"><a href="correlations.html#cb131-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Observations: 300</span></span></code></pre></div>
<p>It appears we were terribly wrong. It seems as if <code>performance</code> and <code>happiness</code> are moderately negatively correlated with each other. Thus, the more a student improves their performance, the less happy teachers, parents and even students are. I hope you agree that this is quite counter-intuitive. However, what could be the cause for such a finding.</p>
<p>It appears we were terribly wrong. It seems as if performance and happiness are moderately negatively correlated with each other. Thus, the more a student improves their performance, the less happy teachers, parents, and students are. I hope you agree that this is quite counter-intuitive. However, what could be the cause for such a finding?</p>
<p>If you have the instincts of a <a href="https://www.imdb.com/title/tt2356777/episodes?season=1" traget="blank" title="True Detective">true detective</a>, you would think that maybe we should look at each group of participants separately. So, let’s plot the same scatterplot again but colour the responses of each participant <code>group</code> differently and also compute the correlation for each subset of our data.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="correlations.html#cb132-1" aria-hidden="true" tabindex="-1"></a>simpson <span class="sc">%&gt;%</span></span>
<span id="cb132-2"><a href="correlations.html#cb132-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(performance, happiness, <span class="at">group =</span> group, colgroup)) <span class="sc">+</span></span>
<span id="cb132-3"><a href="correlations.html#cb132-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb132-4"><a href="correlations.html#cb132-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb132-5"><a href="correlations.html#cb132-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> y <span class="sc">~</span> x,</span>
<span id="cb132-6"><a href="correlations.html#cb132-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb132-7"><a href="correlations.html#cb132-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb132-8"><a href="correlations.html#cb132-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb132-9"><a href="correlations.html#cb132-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Changing colours to make the reference line more visible</span></span>
<span id="cb132-10"><a href="correlations.html#cb132-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#42BDFF&quot;</span>, <span class="st">&quot;#FF5C67&quot;</span>, <span class="st">&quot;#B3AF25&quot;</span>))</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Simpson%20paradox%20plot%20and%20correlation%20all%202-1.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="correlations.html#cb133-1" aria-hidden="true" tabindex="-1"></a>simpson <span class="sc">%&gt;%</span></span>
<span id="cb133-2"><a href="correlations.html#cb133-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span></span>
<span id="cb133-3"><a href="correlations.html#cb133-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlation</span>()</span>
<span id="cb133-4"><a href="correlations.html#cb133-4" aria-hidden="true" tabindex="-1"></a><span class="do">## # Correlation Matrix (pearson-method)</span></span>
<span id="cb133-5"><a href="correlations.html#cb133-5" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb133-6"><a href="correlations.html#cb133-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Group   |  Parameter1 | Parameter2 |    r |       95% CI | t(98) |         p</span></span>
<span id="cb133-7"><a href="correlations.html#cb133-7" aria-hidden="true" tabindex="-1"></a><span class="do">## ----------------------------------------------------------------------------</span></span>
<span id="cb133-8"><a href="correlations.html#cb133-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Parent  | performance |  happiness | 0.65 | [0.52, 0.75] |  8.47 | &lt; .001***</span></span>
<span id="cb133-9"><a href="correlations.html#cb133-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Student | performance |  happiness | 0.65 | [0.52, 0.75] |  8.47 | &lt; .001***</span></span>
<span id="cb133-10"><a href="correlations.html#cb133-10" aria-hidden="true" tabindex="-1"></a><span class="do">## Teacher | performance |  happiness | 0.65 | [0.52, 0.75] |  8.47 | &lt; .001***</span></span>
<span id="cb133-11"><a href="correlations.html#cb133-11" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb133-12"><a href="correlations.html#cb133-12" aria-hidden="true" tabindex="-1"></a><span class="do">## p-value adjustment method: Holm (1979)</span></span>
<span id="cb133-13"><a href="correlations.html#cb133-13" aria-hidden="true" tabindex="-1"></a><span class="do">## Observations: 100</span></span></code></pre></div>
<p>The results have magically been inverted. Instead of a negative correlation, we now find a strong positive correlation among all groups. This result seems to make much more sense.</p>
<p>When computing correlations, we need to be aware that subsets of our data might show different directions of correlations. Sometimes insignificant correlations might suddenly become significant.</p>
<p>If your study relies on correlations only to detect relationships between variables, which it hopefully does not, it is essential to investigate whether the detected or undetected correlations exist. Of course, such an investigation can only be based on the data you obtained. The rest remains pure speculation. Nevertheless, correlations are beneficial to review the bilateral relationship of your variables. It is often used as a pre-test for regressions (see Chapter <a href="regression.html#regression">13</a>) and similarly more advanced computations. As a technique to make inferences, the correlation is a good starting point but should be complemented by other steps, if possible.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-cohen1988statistical" class="csl-entry">
Cohen, Jacob. 1988. <span>“Statistical Power Analysis for the Behavioral Sciences New York.”</span> <em>NY: Academic</em>, 54.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="3">
<li id="fn3"><p>If you want to know what people vote on these days, have a look at <a href="https://www.ranker.com">www.ranker.com</a><a href="correlations.html#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sources-of-bias.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="power-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": true,
"weibo": false,
"instapaper": true,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
