<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>12 Regression: Creating models to predict future observations | R for Non-Programmers: A Guide for Social Scientists</title>
  <meta name="description" content="This books is intended for Social Scientists. No matter whether you have years of experiences, this book might come in handy if you never use R or any other programming language before." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="12 Regression: Creating models to predict future observations | R for Non-Programmers: A Guide for Social Scientists" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This books is intended for Social Scientists. No matter whether you have years of experiences, this book might come in handy if you never use R or any other programming language before." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="12 Regression: Creating models to predict future observations | R for Non-Programmers: A Guide for Social Scientists" />
  
  <meta name="twitter:description" content="This books is intended for Social Scientists. No matter whether you have years of experiences, this book might come in handy if you never use R or any other programming language before." />
  

<meta name="author" content="Daniel Dauber" />


<meta name="date" content="2021-09-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="comparing-groups.html"/>
<link rel="next" href="mixed-methods-research-analysing-qualitative-in-r.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for Non-Programmers</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome 👋</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments 🙏</a></li>
<li class="chapter" data-level="1" data-path="readme-before-you-get-started.html"><a href="readme-before-you-get-started.html"><i class="fa fa-check"></i><b>1</b> <code>Readme.</code> Before you get started</a>
<ul>
<li class="chapter" data-level="1.1" data-path="readme-before-you-get-started.html"><a href="readme-before-you-get-started.html#a-starting-point-and-reference-book"><i class="fa fa-check"></i><b>1.1</b> A starting point and reference book</a></li>
<li class="chapter" data-level="1.2" data-path="readme-before-you-get-started.html"><a href="readme-before-you-get-started.html#download-the-companion-r-package"><i class="fa fa-check"></i><b>1.2</b> Download the companion R package</a></li>
<li class="chapter" data-level="1.3" data-path="readme-before-you-get-started.html"><a href="readme-before-you-get-started.html#a-tidyverse-approach-with-some-basic-r"><i class="fa fa-check"></i><b>1.3</b> A ‘tidyverse’ approach with some basic R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="why-learn-a-programming-language-as-a-non-programmer.html"><a href="why-learn-a-programming-language-as-a-non-programmer.html"><i class="fa fa-check"></i><b>2</b> Why learn a programming language as a non-programmer?</a>
<ul>
<li class="chapter" data-level="2.1" data-path="why-learn-a-programming-language-as-a-non-programmer.html"><a href="why-learn-a-programming-language-as-a-non-programmer.html#learning-new-tools-to-analyse-your-data-is-always-essential"><i class="fa fa-check"></i><b>2.1</b> Learning new tools to analyse your data is always essential</a></li>
<li class="chapter" data-level="2.2" data-path="why-learn-a-programming-language-as-a-non-programmer.html"><a href="why-learn-a-programming-language-as-a-non-programmer.html#programming-languages-enhance-your-conceptual-thinking"><i class="fa fa-check"></i><b>2.2</b> Programming languages enhance your conceptual thinking</a></li>
<li class="chapter" data-level="2.3" data-path="why-learn-a-programming-language-as-a-non-programmer.html"><a href="why-learn-a-programming-language-as-a-non-programmer.html#programming-languages-allow-you-to-look-at-your-data-from-a-different-angle"><i class="fa fa-check"></i><b>2.3</b> Programming languages allow you to look at your data from a different angle</a></li>
<li class="chapter" data-level="2.4" data-path="why-learn-a-programming-language-as-a-non-programmer.html"><a href="why-learn-a-programming-language-as-a-non-programmer.html#learning-any-programming-language-will-help-you-learn-other-programming-languages."><i class="fa fa-check"></i><b>2.4</b> Learning any programming language will help you learn other programming languages.</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html"><i class="fa fa-check"></i><b>3</b> Setting up R and RStudio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html#installing-r"><i class="fa fa-check"></i><b>3.1</b> Installing R</a></li>
<li class="chapter" data-level="3.2" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html#installing-rstudio"><i class="fa fa-check"></i><b>3.2</b> Installing RStudio</a></li>
<li class="chapter" data-level="3.3" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html#when-you-first-start-rstudio"><i class="fa fa-check"></i><b>3.3</b> When you first start RStudio</a></li>
<li class="chapter" data-level="3.4" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html#updating-r-and-rstudio"><i class="fa fa-check"></i><b>3.4</b> Updating R and RStudio: Living at the pulse of innovation</a></li>
<li class="chapter" data-level="3.5" data-path="setting-up-r-and-rstudio.html"><a href="setting-up-r-and-rstudio.html#rstudio-cloud"><i class="fa fa-check"></i><b>3.5</b> RStudio Cloud</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html"><i class="fa fa-check"></i><b>4</b> The RStudio Interface</a>
<ul>
<li class="chapter" data-level="4.1" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html#the-console-window"><i class="fa fa-check"></i><b>4.1</b> The Console window</a></li>
<li class="chapter" data-level="4.2" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html#the-source-window"><i class="fa fa-check"></i><b>4.2</b> The Source window</a></li>
<li class="chapter" data-level="4.3" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html#the-environment-history-connections-tutorial-window"><i class="fa fa-check"></i><b>4.3</b> The Environment / History / Connections / Tutorial window</a></li>
<li class="chapter" data-level="4.4" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html#the-files-plots-packages-help-viewer-window"><i class="fa fa-check"></i><b>4.4</b> The Files / Plots / Packages / Help / Viewer window</a></li>
<li class="chapter" data-level="4.5" data-path="the-rstudio-interface.html"><a href="the-rstudio-interface.html#customise-your-user-interface"><i class="fa fa-check"></i><b>4.5</b> Customise your user interface</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html"><i class="fa fa-check"></i><b>5</b> R Basics: The very fundamentals</a>
<ul>
<li class="chapter" data-level="5.1" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#basic-computations-in-r"><i class="fa fa-check"></i><b>5.1</b> Basic computations in R</a></li>
<li class="chapter" data-level="5.2" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#assigning-values-to-objects"><i class="fa fa-check"></i><b>5.2</b> Assigning values to objects: ‘&lt;-’</a></li>
<li class="chapter" data-level="5.3" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#functions"><i class="fa fa-check"></i><b>5.3</b> Functions</a></li>
<li class="chapter" data-level="5.4" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#r-packages"><i class="fa fa-check"></i><b>5.4</b> R packages</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#installing-packages-using-a-function"><i class="fa fa-check"></i><b>5.4.1</b> Installing packages using <code>install.packages()</code></a></li>
<li class="chapter" data-level="5.4.2" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#installing-packages-via-rstudio"><i class="fa fa-check"></i><b>5.4.2</b> Installing packages via RStudio’s package pane</a></li>
<li class="chapter" data-level="5.4.3" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#using-r-packages"><i class="fa fa-check"></i><b>5.4.3</b> Using R Packages</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#coding-etiquette"><i class="fa fa-check"></i><b>5.5</b> Coding etiquette</a></li>
<li class="chapter" data-level="5.6" data-path="r-basics-the-very-fundamentals.html"><a href="r-basics-the-very-fundamentals.html#exercises-chapter-5"><i class="fa fa-check"></i><b>5.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="starting-your-r-projects.html"><a href="starting-your-r-projects.html"><i class="fa fa-check"></i><b>6</b> Starting your R projects</a>
<ul>
<li class="chapter" data-level="6.1" data-path="starting-your-r-projects.html"><a href="starting-your-r-projects.html#creating-an-r-project"><i class="fa fa-check"></i><b>6.1</b> Creating an R Project file</a></li>
<li class="chapter" data-level="6.2" data-path="starting-your-r-projects.html"><a href="starting-your-r-projects.html#organising-your-projects"><i class="fa fa-check"></i><b>6.2</b> Organising your projects</a></li>
<li class="chapter" data-level="6.3" data-path="starting-your-r-projects.html"><a href="starting-your-r-projects.html#creating-an-r-script"><i class="fa fa-check"></i><b>6.3</b> Creating an R Script</a></li>
<li class="chapter" data-level="6.4" data-path="starting-your-r-projects.html"><a href="starting-your-r-projects.html#r-markdown-and-r-notebooks"><i class="fa fa-check"></i><b>6.4</b> Using R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i><b>7</b> Data Wrangling</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-wrangling.html"><a href="data-wrangling.html#import-your-data"><i class="fa fa-check"></i><b>7.1</b> Import your data</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="data-wrangling.html"><a href="data-wrangling.html#import-data-from-the-files-pane"><i class="fa fa-check"></i><b>7.1.1</b> Import data from the Files pane</a></li>
<li class="chapter" data-level="7.1.2" data-path="data-wrangling.html"><a href="data-wrangling.html#importing-data-from-the-environment-pane"><i class="fa fa-check"></i><b>7.1.2</b> Importing data from the Environment pane</a></li>
<li class="chapter" data-level="7.1.3" data-path="data-wrangling.html"><a href="data-wrangling.html#importing-data-using-functions"><i class="fa fa-check"></i><b>7.1.3</b> Importing data using functions directly</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="data-wrangling.html"><a href="data-wrangling.html#inspecting-raw-data"><i class="fa fa-check"></i><b>7.2</b> Inspecting your data</a></li>
<li class="chapter" data-level="7.3" data-path="data-wrangling.html"><a href="data-wrangling.html#colnames-cleaning"><i class="fa fa-check"></i><b>7.3</b> Cleaning your column names: Call the <code>janitor</code></a></li>
<li class="chapter" data-level="7.4" data-path="data-wrangling.html"><a href="data-wrangling.html#change-data-types"><i class="fa fa-check"></i><b>7.4</b> Data types: What are they and how can you change them</a></li>
<li class="chapter" data-level="7.5" data-path="data-wrangling.html"><a href="data-wrangling.html#handling-factors"><i class="fa fa-check"></i><b>7.5</b> Handling factors</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="data-wrangling.html"><a href="data-wrangling.html#recoding-factors"><i class="fa fa-check"></i><b>7.5.1</b> Recoding factors</a></li>
<li class="chapter" data-level="7.5.2" data-path="data-wrangling.html"><a href="data-wrangling.html#reordering-factor-levels"><i class="fa fa-check"></i><b>7.5.2</b> Reordering factor levels</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="data-wrangling.html"><a href="data-wrangling.html#dealing-with-missing-data"><i class="fa fa-check"></i><b>7.6</b> Dealing with missing data</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="data-wrangling.html"><a href="data-wrangling.html#mapping-missing-data"><i class="fa fa-check"></i><b>7.6.1</b> Mapping missing data</a></li>
<li class="chapter" data-level="7.6.2" data-path="data-wrangling.html"><a href="data-wrangling.html#patterns-of-missing-data"><i class="fa fa-check"></i><b>7.6.2</b> Identifying patterns of missing data</a></li>
<li class="chapter" data-level="7.6.3" data-path="data-wrangling.html"><a href="data-wrangling.html#replacing-removing-missing-data"><i class="fa fa-check"></i><b>7.6.3</b> Replacing or removing missing data</a></li>
<li class="chapter" data-level="7.6.4" data-path="data-wrangling.html"><a href="data-wrangling.html#main-takeaways-regarding-dealing-with-missing-data"><i class="fa fa-check"></i><b>7.6.4</b> Main takeaways regarding dealing with missing data</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="data-wrangling.html"><a href="data-wrangling.html#latent-constructs"><i class="fa fa-check"></i><b>7.7</b> Latent constructs and their reliability</a></li>
<li class="chapter" data-level="7.8" data-path="data-wrangling.html"><a href="data-wrangling.html#conclusion-data-wrangling"><i class="fa fa-check"></i><b>7.8</b> Once you finished with data wrangling</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>8</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="8.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#plotting-in-r-with-ggplot2"><i class="fa fa-check"></i><b>8.1</b> Plotting in R with <code>ggplot2</code></a></li>
<li class="chapter" data-level="8.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#central-tendency"><i class="fa fa-check"></i><b>8.2</b> Central tendency measures: Mean, Median, Mode</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean"><i class="fa fa-check"></i><b>8.2.1</b> Mean</a></li>
<li class="chapter" data-level="8.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#median"><i class="fa fa-check"></i><b>8.2.2</b> Median</a></li>
<li class="chapter" data-level="8.2.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mode"><i class="fa fa-check"></i><b>8.2.3</b> Mode</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#spread-of-data"><i class="fa fa-check"></i><b>8.3</b> Indicators and visualisations to examine the spread of data</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#boxplot-so-much-information-in-just-one-box"><i class="fa fa-check"></i><b>8.3.1</b> Boxplot: So much information in just one box</a></li>
<li class="chapter" data-level="8.3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#histogram-do-not-mistake-it-as-a-bar-plot"><i class="fa fa-check"></i><b>8.3.2</b> Histogram: Do not mistake it as a bar plot</a></li>
<li class="chapter" data-level="8.3.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#density-plots-your-smooth-histograms"><i class="fa fa-check"></i><b>8.3.3</b> Density plots: Your smooth histograms</a></li>
<li class="chapter" data-level="8.3.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#violin-plot-your-smooth-boxplot"><i class="fa fa-check"></i><b>8.3.4</b> Violin plot: Your smooth boxplot</a></li>
<li class="chapter" data-level="8.3.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#qq-plot"><i class="fa fa-check"></i><b>8.3.5</b> QQ plot: A ‘cute’ plot to check for normality in your data</a></li>
<li class="chapter" data-level="8.3.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#standard-deviation"><i class="fa fa-check"></i><b>8.3.6</b> Standard deviation: Your average deviation from the mean</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="sources-of-bias.html"><a href="sources-of-bias.html"><i class="fa fa-check"></i><b>9</b> Sources of bias: Outliers, normality and other ‘conundrums’</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sources-of-bias.html"><a href="sources-of-bias.html#additivity-and-linearity"><i class="fa fa-check"></i><b>9.1</b> Linearity and additivity</a></li>
<li class="chapter" data-level="9.2" data-path="sources-of-bias.html"><a href="sources-of-bias.html#independence"><i class="fa fa-check"></i><b>9.2</b> Independence</a></li>
<li class="chapter" data-level="9.3" data-path="sources-of-bias.html"><a href="sources-of-bias.html#normality"><i class="fa fa-check"></i><b>9.3</b> Normality</a></li>
<li class="chapter" data-level="9.4" data-path="sources-of-bias.html"><a href="sources-of-bias.html#homogeneity-of-variance"><i class="fa fa-check"></i><b>9.4</b> Homogeneity of variance (homoscedasticity)</a></li>
<li class="chapter" data-level="9.5" data-path="sources-of-bias.html"><a href="sources-of-bias.html#dealing-with-outliers"><i class="fa fa-check"></i><b>9.5</b> Outliers and how to deal with them</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="sources-of-bias.html"><a href="sources-of-bias.html#ouliers-standard_deviation"><i class="fa fa-check"></i><b>9.5.1</b> Detecting outliers using the standard deviation</a></li>
<li class="chapter" data-level="9.5.2" data-path="sources-of-bias.html"><a href="sources-of-bias.html#outliers-iqr"><i class="fa fa-check"></i><b>9.5.2</b> Detecting outliers using the interquartile range</a></li>
<li class="chapter" data-level="9.5.3" data-path="sources-of-bias.html"><a href="sources-of-bias.html#removing-or-replacing-outliers"><i class="fa fa-check"></i><b>9.5.3</b> Removing or replacing outliers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlations.html"><a href="correlations.html"><i class="fa fa-check"></i><b>10</b> Correlations</a>
<ul>
<li class="chapter" data-level="10.1" data-path="correlations.html"><a href="correlations.html#parametric-or-non-parametric"><i class="fa fa-check"></i><b>10.1</b> Parametric or non-parametric: That is the question</a></li>
<li class="chapter" data-level="10.2" data-path="correlations.html"><a href="correlations.html#plotting-correlations"><i class="fa fa-check"></i><b>10.2</b> Plotting correlations</a></li>
<li class="chapter" data-level="10.3" data-path="correlations.html"><a href="correlations.html#significance"><i class="fa fa-check"></i><b>10.3</b> Significance: A way to help you judge your findings</a></li>
<li class="chapter" data-level="10.4" data-path="correlations.html"><a href="correlations.html#limitations-of-correlations"><i class="fa fa-check"></i><b>10.4</b> Limitations of correlations</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="correlations.html"><a href="correlations.html#correlations-are-not-causal-relationships"><i class="fa fa-check"></i><b>10.4.1</b> Correlations are not causal relationships</a></li>
<li class="chapter" data-level="10.4.2" data-path="correlations.html"><a href="correlations.html#correlations-can-be-spurious"><i class="fa fa-check"></i><b>10.4.2</b> Correlations can be spurious</a></li>
<li class="chapter" data-level="10.4.3" data-path="correlations.html"><a href="correlations.html#simpsons-paradox"><i class="fa fa-check"></i><b>10.4.3</b> Simpson’s Paradox: When correlations betray you</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="comparing-groups.html"><a href="comparing-groups.html"><i class="fa fa-check"></i><b>11</b> Comparing groups</a>
<ul>
<li class="chapter" data-level="11.1" data-path="comparing-groups.html"><a href="comparing-groups.html#comparability-apples-vs-oranges"><i class="fa fa-check"></i><b>11.1</b> Comparability: Apples vs Oranges</a></li>
<li class="chapter" data-level="11.2" data-path="comparing-groups.html"><a href="comparing-groups.html#comparing-two-groups"><i class="fa fa-check"></i><b>11.2</b> Comparing two groups</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="comparing-groups.html"><a href="comparing-groups.html#two-unpaired-groups"><i class="fa fa-check"></i><b>11.2.1</b> Two Unpaired groups</a></li>
<li class="chapter" data-level="11.2.2" data-path="comparing-groups.html"><a href="comparing-groups.html#two-paired-groups"><i class="fa fa-check"></i><b>11.2.2</b> Two Paired groups</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="comparing-groups.html"><a href="comparing-groups.html#comparing-more-than-two-groups"><i class="fa fa-check"></i><b>11.3</b> Comparing more than two groups</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="comparing-groups.html"><a href="comparing-groups.html#multiple-unpaired-groups"><i class="fa fa-check"></i><b>11.3.1</b> Multiple unpaired groups</a></li>
<li class="chapter" data-level="11.3.2" data-path="comparing-groups.html"><a href="comparing-groups.html#multiple-paired-groups"><i class="fa fa-check"></i><b>11.3.2</b> Multiple paired groups</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="comparing-groups.html"><a href="comparing-groups.html#chi-squared-test"><i class="fa fa-check"></i><b>11.4</b> Comparing groups based on factors: Contingency tables</a></li>
<li class="chapter" data-level="11.5" data-path="comparing-groups.html"><a href="comparing-groups.html#cheatsheet-group-comparisons"><i class="fa fa-check"></i><b>11.5</b> A cheatsheet to guide your own group comparisons</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>12</b> Regression: Creating models to predict future observations</a>
<ul>
<li class="chapter" data-level="12.1" data-path="regression.html"><a href="regression.html#single-linear-regression"><i class="fa fa-check"></i><b>12.1</b> Single linear regression</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="regression.html"><a href="regression.html#fitting-a-regression-model-by-hand"><i class="fa fa-check"></i><b>12.1.1</b> Fitting a regression model by hand, i.e. trial and error</a></li>
<li class="chapter" data-level="12.1.2" data-path="regression.html"><a href="regression.html#fitting-a-regression-model-computationally"><i class="fa fa-check"></i><b>12.1.2</b> Fitting a regression model computationally</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="regression.html"><a href="regression.html#multiple-regression"><i class="fa fa-check"></i><b>12.2</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="regression.html"><a href="regression.html#outliers-in-multiple-regressions"><i class="fa fa-check"></i><b>12.2.1</b> Outliers in multiple regressions</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="regression.html"><a href="regression.html#hierarchical-regression"><i class="fa fa-check"></i><b>12.3</b> Hierarchical regression</a></li>
<li class="chapter" data-level="12.4" data-path="regression.html"><a href="regression.html#moderated-regressions"><i class="fa fa-check"></i><b>12.4</b> Moderated regression</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="mixed-methods-research-analysing-qualitative-in-r.html"><a href="mixed-methods-research-analysing-qualitative-in-r.html"><i class="fa fa-check"></i><b>13</b> Mixed-methods research: Analysing qualitative in R</a></li>
<li class="chapter" data-level="14" data-path="next-steps.html"><a href="next-steps.html"><i class="fa fa-check"></i><b>14</b> Where to go from here: The next steps in your R journey</a>
<ul>
<li class="chapter" data-level="14.1" data-path="next-steps.html"><a href="next-steps.html#next-steps-github"><i class="fa fa-check"></i><b>14.1</b> GitHub: A Gateway to even more ingenious R packages</a></li>
<li class="chapter" data-level="14.2" data-path="next-steps.html"><a href="next-steps.html#next-steps-books"><i class="fa fa-check"></i><b>14.2</b> Books to read and expand your knowledge</a></li>
<li class="chapter" data-level="14.3" data-path="next-steps.html"><a href="next-steps.html#next-steps-online-readings"><i class="fa fa-check"></i><b>14.3</b> Engage in regular online readings about R</a></li>
<li class="chapter" data-level="14.4" data-path="next-steps.html"><a href="next-steps.html#next-steps-twitter"><i class="fa fa-check"></i><b>14.4</b> Join the Twitter community and hone your skills</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix</a>
<ul>
<li class="chapter" data-level="14.5" data-path="appendix.html"><a href="appendix.html#comparing-two-unpaired-groups"><i class="fa fa-check"></i><b>14.5</b> Comparing two unpaired groups</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="exercises-solutions.html"><a href="exercises-solutions.html"><i class="fa fa-check"></i><b>15</b> Exercises: Solutions</a>
<ul>
<li class="chapter" data-level="15.1" data-path="exercises-solutions.html"><a href="exercises-solutions.html#exercises-solutions-5"><i class="fa fa-check"></i><b>15.1</b> Solutions for 5.6</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://twitter.com/daniel_dauber" target="blank">Find me on twitter!</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for Non-Programmers: A Guide for Social Scientists</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression" class="section level1" number="12">
<h1><span class="header-section-number">12</span> Regression: Creating models to predict future observations</h1>
<p>Regressions are an interesting area of data analysis since it enables us to make very specific predictions about the future incorporating different variables at the same time. As the name implies, regressions ‘regress,’ i.e. they draw on past observations to make predictions about future observations. Thus, any analysis incorporating a regression makes the implicit assumption that the future can be best explained by the past.</p>
<p>I once heard someone refer to regressions as driving a car by looking at the rearview mirror. As long as the road is straight, we will be able to successfully navigate the car. However, if there is a sudden turn, we might drive into the abyss. This makes it very clear when and how regressions are can be helpful.</p>
<p>Regressions are also a machine learning method, which falls under models with supervised learning. If you find machine learning fascinating, you might find the book “Hands-on Machine Learning with R” <span class="citation">(<a href="#ref-boehmke2019hands" role="doc-biblioref">Boehmke and Greenwell 2019</a>)</span> very insightful and interesting.</p>
<p>In the following chapters we will cover three common types of regressions:</p>
<ul>
<li><p>Single linear regression</p></li>
<li><p>Multiple regression</p></li>
<li><p>Hierarchical regression</p></li>
</ul>
<p>These three types will allow you to perform any other type of linear regression you could think of. We can further distinguish two approaches to modelling via regressions:</p>
<ul>
<li><p><em>hypothesis testing</em>: A regression model is defined ex-ante</p></li>
<li><p><em>machine learning</em>: A model is developed based on empirical data</p></li>
</ul>
<p>In the following chapters we will slightly blur the lines between both approaches.</p>
<p>All our regressions will be performed using the <code>covid</code> dataset of the <code>r4np</code> package to investigate whether certain factors can predict COVID numbers in different countries. I felt, this book would not have been complete without covering this topic. After all, I wrote this book during the pandemic and it likely will mark a dark chapter in human history.</p>
<div id="single-linear-regression" class="section level2" number="12.1">
<h2><span class="header-section-number">12.1</span> Single linear regression</h2>
<p>A single linear regression looks very similar to a correlation (see Chapter <a href="correlations.html#correlations">10</a>, but it is different in that it defines which variable affects another variable, i.e. a single direction relationship. I used the terms dependent variable (DV) and independent variable (IV) previously when comparing groups (see Chapter <a href="comparing-groups.html#comparing-groups">11</a>, and we will use them here again. In group comparisons, the independent variable was usually a <code>factor</code>, but in regressions we can use data that is not a categorical variable, i.e. <code>integer</code>, <code>double</code>, etc.</p>
<p>While I understand that mathematical equations can be confusing, with regressions, they are fairly simple to understand. Also, when writing our models in R, we will continuously use a <code>formula</code> to specify our regression. A single linear regression consists of one independent variable and one dependent variable:</p>
<div align="center">
<p><span class="math display">\[
DV = \beta_{0} + IV * \beta_{1} + error
\]</span></p>
</div>
<p>Beta (<span class="math inline">\(\beta\)</span>) represents the coefficient of the independent variable, i.e. how much a change in IV causes a change in DV. For example, a one unit change in the IV might mean that the DV changes by two units of IV:</p>
<div id="single-linear-regression-example" align="center">
<p><span class="math display">\[
DV = \beta_0 + 2 * IV + error
\]</span></p>
</div>
<p>If we ignore <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(error\)</span> for a moment, we find that that if <span class="math inline">\(IV = 3\)</span>, our <span class="math inline">\(DV = 2*3 = 6\)</span>. Therefore, if <span class="math inline">\(IV = 5\)</span>, we find that <span class="math inline">\(DV = 10\)</span>, and so on. According to this model, DV will always be twice as large as IV.</p>
<p>You might be wondering what <span class="math inline">\(\beta_0\)</span> stands for. It indicates an offset for each value, also called the intercept. Thus, no matter which value we choose for IV, DV will always be <span class="math inline">\(\beta_0\)</span> different from IV. It is a constant in our model. This can be best explained by visualising a regression line. Pay particular attention to the to the expressions after <code>function(x)</code></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="regression.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A: Two models with different beta(0)</span></span>
<span id="cb1-2"><a href="regression.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb1-3"><a href="regression.html#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="dv">2</span> <span class="sc">*</span> x, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb1-4"><a href="regression.html#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> x, <span class="at">colour =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb1-5"><a href="regression.html#cb1-5" aria-hidden="true" tabindex="-1"></a>  see<span class="sc">::</span><span class="fu">theme_modern</span>()</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/beta%20zero%20and%20beta%20one%20explained-1.png" width="672" /></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="regression.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># B: Two models with the same beta(0), but different beta(1)</span></span>
<span id="cb2-2"><a href="regression.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb2-3"><a href="regression.html#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="dv">2</span> <span class="sc">*</span> x, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="regression.html#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="dv">3</span> <span class="sc">*</span> x, <span class="at">colour =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="regression.html#cb2-5" aria-hidden="true" tabindex="-1"></a>  see<span class="sc">::</span><span class="fu">theme_modern</span>()</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/beta%20zero%20and%20beta%20one%20explained-2.png" width="672" /></p>
<p>Plot B also shows what happens if we change <span class="math inline">\(\beta_1\)</span>, i.e. the slope. The two models both have the same intercept (and therefore the same origin), but the blue line ascends quicker than the red one, because its <span class="math inline">\(\beta_1\)</span> is higher than the one for the red model.</p>
<p>Lastly, the <span class="math inline">\(error\)</span> component in the regression model refers to the deviation of data from this regression lines. Ideally, we want this value to be as small as possible.</p>
<div id="fitting-a-regression-model-by-hand" class="section level3" number="12.1.1">
<h3><span class="header-section-number">12.1.1</span> Fitting a regression model by hand, i.e. trial and error</h3>
<p>If this sounds all awfully theoretical, let’s try to fit a regression model by hand. First we need to consider what our model should be able to predict. Let’s say that the number of COVID-19 cases predicts the number of deaths due to COVID-19. Intuitively we would assume this should be a linear relationship, because the more cases there are, the more likely we find more deaths caused by it.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="regression.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We only select most recent numbers, i.e. &quot;2021-08-26&quot;</span></span>
<span id="cb3-2"><a href="regression.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and countries which have COVID cases</span></span>
<span id="cb3-3"><a href="regression.html#cb3-3" aria-hidden="true" tabindex="-1"></a>covid_sample <span class="ot">&lt;-</span> covid <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="regression.html#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(date_reported <span class="sc">==</span> <span class="st">&quot;2021-08-26&quot;</span> <span class="sc">&amp;</span></span>
<span id="cb3-5"><a href="regression.html#cb3-5" aria-hidden="true" tabindex="-1"></a>           cumulative_cases <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb3-6"><a href="regression.html#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="regression.html#cb3-7" aria-hidden="true" tabindex="-1"></a>covid_sample <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="regression.html#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cumulative_cases,</span>
<span id="cb3-9"><a href="regression.html#cb3-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> cumulative_deaths)) <span class="sc">+</span></span>
<span id="cb3-10"><a href="regression.html#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Finding%20a%20regression%20equation%20by%20hand%20p1-1.png" width="672" /></p>
<p>This data visualisation shows us not much. We can see that there are three countries, which appear to have considerably more cases than most other countries. Thus, all other countries are crammed together in the bottom left corner. To improve this visualisation without removing the outliers, we can rescale the x and y axis using the function <code>scale_x_continuous()</code> and <code>scale_y_continuous()</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="regression.html#cb4-1" aria-hidden="true" tabindex="-1"></a>covid_sample <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="regression.html#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cumulative_cases,</span>
<span id="cb4-3"><a href="regression.html#cb4-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> cumulative_deaths)) <span class="sc">+</span></span>
<span id="cb4-4"><a href="regression.html#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-5"><a href="regression.html#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">&quot;log&quot;</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="regression.html#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">trans =</span> <span class="st">&quot;log&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Finding%20a%20regression%20equation%20by%20hand%20p2-1.png" width="672" /></p>
<p>As we can see, the scatterplot is now easier to read and the dots are more spread out. This reveals that there is quite a strong relationship between <code>cumulative_cases</code> and <code>cumulative_deaths</code>. However, similar to before, we should avoid outliers when performing our analysis. For the sake of simplicity, in this section I will limit the number of countries included in our analysis, which also removes the requirement of using <code>scale_x_continuous()</code> and <code>scale_y_continuous()</code>.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="regression.html#cb5-1" aria-hidden="true" tabindex="-1"></a>covid_sample <span class="ot">&lt;-</span> covid_sample <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="regression.html#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(date_reported <span class="sc">==</span> <span class="st">&quot;2021-08-26&quot;</span> <span class="sc">&amp;</span></span>
<span id="cb5-3"><a href="regression.html#cb5-3" aria-hidden="true" tabindex="-1"></a>           cumulative_cases <span class="sc">&gt;=</span> <span class="dv">2500</span> <span class="sc">&amp;</span></span>
<span id="cb5-4"><a href="regression.html#cb5-4" aria-hidden="true" tabindex="-1"></a>           cumulative_cases <span class="sc">&lt;=</span> <span class="dv">150000</span> <span class="sc">&amp;</span></span>
<span id="cb5-5"><a href="regression.html#cb5-5" aria-hidden="true" tabindex="-1"></a>           cumulative_deaths <span class="sc">&lt;=</span> <span class="dv">3000</span>)</span>
<span id="cb5-6"><a href="regression.html#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="regression.html#cb5-7" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">&lt;-</span> covid_sample <span class="sc">%&gt;%</span></span>
<span id="cb5-8"><a href="regression.html#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cumulative_cases,</span>
<span id="cb5-9"><a href="regression.html#cb5-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> cumulative_deaths)) <span class="sc">+</span></span>
<span id="cb5-10"><a href="regression.html#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span>
<span id="cb5-11"><a href="regression.html#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="regression.html#cb5-12" aria-hidden="true" tabindex="-1"></a>plot</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Finding%20a%20regression%20equation%20by%20hand%20p3-1.png" width="672" /></p>
<p>Through trial and error we can try to fit a linear line on top by adjusting the beta values. This is effectively what we hope to achieve with a regression: the best <span class="math inline">\(\beta\)</span> values which best explain our data. Let’s start with the basic assumption of <span class="math inline">\(y = x\)</span> without specific <span class="math inline">\(\beta\)</span>s, i.e. they are zero.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="regression.html#cb6-1" aria-hidden="true" tabindex="-1"></a>plot <span class="sc">+</span></span>
<span id="cb6-2"><a href="regression.html#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) x, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Finding%20a%20regression%20equation%20by%20hand%20p4-1.png" width="672" /></p>
<p>What we try to achieve is that the red line fits nicely inside the cloud of dots. Our very simple model provides a very poor fit to our data points, because all the dots are way below it. This makes sense, because <span class="math inline">\(y = x\)</span> would imply that every COVID-19 case leads to a death, i.e. everyone with COVID did not survive. From our own experience we know that this is luckily not true. Ideally we want the line to be less steep, because our first model does not make much sense. We can do this by adding a <span class="math inline">\(\beta_1\)</span> to our equation. Maybe only 2% of people who got COVID-19 might not have recovered, i.e. <span class="math inline">\(\beta_1 = 0.02\)</span>.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="regression.html#cb7-1" aria-hidden="true" tabindex="-1"></a>plot <span class="sc">+</span></span>
<span id="cb7-2"><a href="regression.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fl">0.02</span><span class="sc">*</span>x, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Finding%20a%20regression%20equation%20by%20hand%20p5-1.png" width="672" /></p>
<p>This time the line looks much more aligned with our observations. One could argue that it might have to move a little to the right as well, to cover the observations at the bottom a bit better. Therefore, we should add a <span class="math inline">\(\beta_0\)</span> to our equation, e.g. <code>-50</code>.= to move it to the right and tweak the <span class="math inline">\(\beta_1\)</span> ever so slightly.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="regression.html#cb8-1" aria-hidden="true" tabindex="-1"></a>plot <span class="sc">+</span></span>
<span id="cb8-2"><a href="regression.html#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="sc">-</span><span class="dv">50</span> <span class="sc">+</span> <span class="fl">0.015</span><span class="sc">*</span>x, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Finding%20a%20regression%20equation%20by%20hand%20p6-1.png" width="672" /></p>
<p>We finished creating our regression model. If we wanted to express it as a formula we would write <span class="math inline">\(DV = -5 + 0.015 * IV\)</span>. We could now use this model to predict how high COVID cases likely will be in other countries.</p>
</div>
<div id="fitting-a-regression-model-computationally" class="section level3" number="12.1.2">
<h3><span class="header-section-number">12.1.2</span> Fitting a regression model computationally</h3>
<p>Estimating a regression model by hand is not ideal and far from accurate. Instead, we would compute the <span class="math inline">\(\beta\)</span>s based on our observed data, i.e. <code>cumulative_cases</code> and <code>cumulative_deaths</code>. We can use the function <code>lm()</code> to achieve this. I also rounded the all <code>numeric</code> values to two decimal places to make the output easier to read. We also use <code>tidy()</code> to retrieve a cleaner output from the computation.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="regression.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># classic r</span></span>
<span id="cb9-2"><a href="regression.html#cb9-2" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(cumulative_deaths <span class="sc">~</span> cumulative_cases, <span class="at">data =</span> covid_sample)</span>
<span id="cb9-3"><a href="regression.html#cb9-3" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(m0) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), round, <span class="dv">2</span>))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   term             estimate std.error statistic p.value
##   &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)         88.1       70.5      1.25    0.21
## 2 cumulative_cases     0.01       0       10.7     0</code></pre>
<p>We first might notice that the <code>p.value</code> indicates that the relationship between <code>cumulative death</code> and <code>cumulative_cases</code> is significant. Thus, we can conclude that countries with more COVID cases also suffer higher numbers of people who do not successfully recover from it. However, you might be wondering where our <span class="math inline">\(\beta\)</span> scores are. They are found where it says <code>estimate</code>. The standard error (<code>std.error</code>) denotes the <code>error</code> we specified in the <a href="regression.html#single-linear-regression">previous equation</a>. We find that in the first row we get the <span class="math inline">\(\beta_0\)</span>, i.e. the one for the intercept which is 88.10. This one is larger than what we estimated, i.e. <code>-50</code>. However, <span class="math inline">\(\beta_1\)</span> is 0.01, which means we have done a very good job in guessing this estimate. Still, it becomes hopefully obvious that it is much easier to use the function <code>lm()</code> to estimate a model than ‘eyeballing it.’</p>
<p>We can now visualise the computed model (in blue) and our guessed model (in red) in one plot and see the differences. The plot shows that we have not been too far off. However, it was relatively easy to fit a model onto the observed data in this case. Often, it is much more difficult, especially when more than two variables are involved.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="regression.html#cb11-1" aria-hidden="true" tabindex="-1"></a>plot <span class="sc">+</span></span>
<span id="cb11-2"><a href="regression.html#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="sc">-</span><span class="dv">50</span> <span class="sc">+</span> <span class="fl">0.015</span><span class="sc">*</span>x, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="regression.html#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fl">88.1</span> <span class="sc">+</span> <span class="fl">0.01</span><span class="sc">*</span>x, <span class="at">colour =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Showing%20computed%20and%20guessed%20regression-1.png" width="672" /></p>
<p>With our final model computed, we also need to check its quality in terms of predictive power based on how well it can actually explain our observed data. We have tested models before when we looked at confirmatory factor analyses for latent variables (see Chapter <a href="data-wrangling.html#latent-constructs">7.7</a>. This time we want to know how accurate our model is in explaining observed data and therefore how accurate it will be predicting future observations. The package <code>performance</code> offers a nice little shortcut to compute many different things at once:</p>
<ul>
<li><p><code>check_model()</code>: Checks for linearity, homogeneity, collinearity and outliers</p></li>
<li><p><code>model_performance()</code>: Tests the quality of our model.</p></li>
</ul>
<p>For now, we are mainly interested in the performance of our model. So, we can compute it the following way:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="regression.html#cb12-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">model_performance</span>(m0)</span></code></pre></div>
<pre><code>## # Indices of model performance
## 
## AIC      |      BIC |    R2 | R2 (adj.) |    RMSE |   Sigma
## -----------------------------------------------------------
## 1472.626 | 1480.319 | 0.548 |     0.543 | 502.573 | 507.891</code></pre>
<p>There are quite a number of performance indicators and here is how to read them:</p>
<ul>
<li><p><code>AIC</code> stands for <em>Akaike Information Criterion</em> and the lower the score the better the model</p></li>
<li><p><code>BIC</code> stands for <em>Bayesian Information Criterion</em> and the lower the score the better the model</p></li>
<li><p><code>R2</code> stands for <em>R squared</em> (<span class="math inline">\(R^2\)</span>) and is also known as the coefficient of determination. It measures how much the independent variable can explain the variance in the dependent variable. In other words, the higher <span class="math inline">\(R^2\)</span> the better is our model, because more of the variance can be explained by our model. <span class="math inline">\(R^2\)</span> falls between 0-1, where 1 would imply that our model can explain 100% of the variance in our sample. <span class="math inline">\(R^2\)</span> is also considered a <em>goodness-of-fit measure</em>.</p></li>
<li><p><code>R2 (adj.)</code> stands for <em>adjusted R squared</em>. The adjusted version of <span class="math inline">\(R^2\)</span> becomes important if we have more than one preditor (i.e. independent variable) in our regression. The adjustment of <span class="math inline">\(R^2\)</span> accounts for the number of independent variables in our model. Thus, it is possible for us to compare different models with each other, even though they might have different numbers of predictors. It is important to note that <span class="math inline">\(R^2\)</span> will always increase if we add more predictors.</p></li>
<li><p><code>RMSE</code> stands for <em>Root Mean Square Error</em> and is an indicate how small or large the prediction error of the model is. Conceptually, it aims to measure the average deviations of values from our model when we attempt predictions. The lower the score the better, i.e. a score of 0 would imply that our model perfectly fits the data, which is likely never the case in the field of Social Sciences. The RMSE is particularly useful when trying to compare models.</p></li>
<li><p><code>Sigma</code> stands for the standard deviation of our residuals (the difference between predicted and empirically observed values) and is therefore a measure of prediction accuracy. <code>Sigma</code> is <em>‘a measure of the average distance each observation falls from its prediction from the model’</em> <span class="citation">(<a href="#ref-gelman2020regression" role="doc-biblioref">Gelman, Hill, and Vehtari 2020, 168</a>)</span>.</p></li>
</ul>
<p>Many of these indices will become more relevant when we compare models. However, <span class="math inline">\(R^2\)</span> can also be meaningfully interpreted without a reference model. We know that the bigger <span class="math inline">\(R^2\)</span> the better. In our case it is <code>0.548</code> which is very good considering that our model consist of only one predictor only. It is not easy to interpret whether an particular <span class="math inline">\(R^2\)</span> value is good or bad. In our simple single linear regression, <span class="math inline">\(R^2\)</span> is literally ‘r squared,’ which we already know from correlations and their effect sizes (see Table <a href="#tab:effect-size-cohen"><strong>??</strong></a>. Thus, if we take the square root of <span class="math inline">\(R^2\)</span> we can retrieve the correlation coefficient, i.e. <span class="math inline">\(r = \sqrt{R^2} = \sqrt{0.548} = 0.740\)</span>. According to <span class="citation"><a href="#ref-cohen1988statistical" role="doc-biblioref">J. Cohen</a> (<a href="#ref-cohen1988statistical" role="doc-biblioref">1988</a>)</span>, this would count as a large effect size.</p>
<p>However, for multiple regressions, the situation is slightly more complicated, but the interpretation of <span class="math inline">\(R^2\)</span> and its adjusted version remain largely the same.</p>
<p>Once you have a model and it is fairly accurate, you can start making predictions. This can be achieved by using our model object <code>m0</code> in combination with the function <code>predict()</code>. However, first we should define a set of values for our independent variable, i.e. <code>cumulative_cases</code>, which we store in a tibble using the <code>tribble()</code> function.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="regression.html#cb14-1" aria-hidden="true" tabindex="-1"></a>df_predict <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb14-2"><a href="regression.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>cumulative_cases,</span>
<span id="cb14-3"><a href="regression.html#cb14-3" aria-hidden="true" tabindex="-1"></a>                <span class="dv">100</span>,</span>
<span id="cb14-4"><a href="regression.html#cb14-4" aria-hidden="true" tabindex="-1"></a>               <span class="dv">1000</span>,</span>
<span id="cb14-5"><a href="regression.html#cb14-5" aria-hidden="true" tabindex="-1"></a>              <span class="dv">10000</span>,</span>
<span id="cb14-6"><a href="regression.html#cb14-6" aria-hidden="true" tabindex="-1"></a>             <span class="dv">100000</span></span>
<span id="cb14-7"><a href="regression.html#cb14-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-8"><a href="regression.html#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m0, <span class="at">newdata =</span> df_predict)</span></code></pre></div>
<pre><code>##          1          2          3          4 
##   89.53289  102.45411  231.66629 1523.78810</code></pre>
<p>As a result we find out how many likely deaths from COVID have to be expected based on our model for each value in our dataset.</p>
<p>Single linear regressions are simple and a good way to introduce novice scholars to modeling social phenomena. However, hardly ever will find that a single variable can explain enough variance to be a useful model. Instead, we most likely can improve the majority of our single regression models by considering more variables in the form of multiple regressions.</p>
</div>
</div>
<div id="multiple-regression" class="section level2" number="12.2">
<h2><span class="header-section-number">12.2</span> Multiple regression</h2>
<p>Multiple regressions expand single linear regressions by allowing us to add more variables. Maybe less surprising, computing a multiple regression is similar to a single regression in R, because it requires the same function, i.e. <code>lm()</code>. However, we add more IVs. Therefore, the equation we used before needs to be modified slightly by adding more independent variables each of which will have its own <span class="math inline">\(\beta\)</span> value:</p>
<div align="center">
<p><span class="math display">\[
DV = \beta_{0} + IV_{1} * \beta_{1} + IV_{2} * \beta_{2} + ... + IV_{n} * \beta_{n} + error
\]</span></p>
</div>
<p>In the last section we wanted to know how many people will likely not recover from COVID. However, it might be even more interesting to understand how we can predict new cases and prevent casualties from the outset. Since I live in the United Kingdom at the time of the pandemic, I am curious to know whether certain COVID measures helped to reduce the number of new cases there. To keep it more interesting, I will also add Germany to the mix since it has shown to be very effective in handling the pandemic relative to other European countries. Of course, feel free to pick different countries (maybe the one you live in?) to follow with my example. In Chapter <a href="regression.html#moderated-regressions">12.4</a> it will become obvious why I chose two countries (#spoiler-alert).</p>
<p>First, we create a dataset that only contains information from the <code>United Kingdom</code> and <code>Germany</code><a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>, which means we use <code>filter()</code>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="regression.html#cb16-1" aria-hidden="true" tabindex="-1"></a>covid_uk_ger <span class="ot">&lt;-</span> covid <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="regression.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(iso3 <span class="sc">==</span> <span class="st">&quot;GBR&quot;</span> <span class="sc">|</span> iso3 <span class="sc">==</span> <span class="st">&quot;DEU&quot;</span>)</span></code></pre></div>
<p>In a next step, we might want to know how new cases are distributed over time. It is always a good idea to inspect the dependent variable to also get a feeling of how much variance there is in your data. Having a bigger range of data values is ideal because the regression model will be able to consider low and high values of the dependent variable instead of just high or low scores. Let’s plot the DV <code>new_cases</code> across time to see when and how much new COVID cases had to be reported.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="regression.html#cb17-1" aria-hidden="true" tabindex="-1"></a>covid_uk_ger <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="regression.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> date_reported,</span>
<span id="cb17-3"><a href="regression.html#cb17-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> new_cases)) <span class="sc">+</span></span>
<span id="cb17-4"><a href="regression.html#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Multiple%20regression%20plotting%20new%20cases-1.png" width="672" /></p>
<p>We can tell that there are different waves of new cases. As such, we should find that there are certain variables that should help explain when <code>new_cases</code> are high and when they are low. If you have hypotheses you want to test, you would already know which variables to include in your regression. However, in our case, we do not really have a hypothesis based on our prior reading or other studies. Thus, we pick variables of interest that we suspect could help us with modelling new COVID cases. We can be fairly certain that the number of new COVID cases should be lower if there are more safety measures in place - assuming that they are effective and adhered to, of course. The <code>covid</code> dataset includes such information evaluated by the <a href="https://covid19.who.int/info/" target="blank" title="WHO">WHO</a>, i.e. <code>masks</code>, <code>travel</code>, <code>gatherings</code>, <code>schools</code> and <code>movements</code>. Remember, you can always find out what these variables stand for by typing <code>?covid</code> into the console. A higher value for these variables indicates that there were more safety measures. Scores can range from 0 (i.e. no measures) to 100 (all WHO measures taken).</p>
<p>We simply add these variables by using the <code>+</code> symbol in the <code>lm()</code> function.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="regression.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create our model</span></span>
<span id="cb18-2"><a href="regression.html#cb18-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(new_cases <span class="sc">~</span> masks <span class="sc">+</span> movements <span class="sc">+</span> gatherings <span class="sc">+</span> schools <span class="sc">+</span> businesses <span class="sc">+</span> travel,</span>
<span id="cb18-3"><a href="regression.html#cb18-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> covid_uk_ger)</span>
<span id="cb18-4"><a href="regression.html#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="regression.html#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect the model specifications</span></span>
<span id="cb18-6"><a href="regression.html#cb18-6" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(m1)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)  -2585.     745.       -3.47 5.43e- 4
## 2 masks          -14.8      9.18     -1.61 1.08e- 1
## 3 movements      -54.7     15.5      -3.52 4.43e- 4
## 4 gatherings     -26.0     19.8      -1.31 1.91e- 1
## 5 schools        394.      29.7      13.2  2.28e-37
## 6 businesses      93.7     13.8       6.79 1.77e-11
## 7 travel          49.5      9.30      5.32 1.22e- 7</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="regression.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the quality of our model</span></span>
<span id="cb20-2"><a href="regression.html#cb20-2" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">model_performance</span>(m1)</span></code></pre></div>
<pre><code>## # Indices of model performance
## 
## AIC       |       BIC |    R2 | R2 (adj.) |      RMSE |     Sigma
## -----------------------------------------------------------------
## 25277.622 | 25318.262 | 0.233 |     0.229 | 10027.204 | 10056.877</code></pre>
<p>Overall (and purely subjectively judged), the model is not particularly great, because even though we added so many variables, the <span class="math inline">\(adjusted \ R^2\)</span> is not particularly high, i.e. ‘only’ 0.229. As mentioned earlier, for multiple regression it is better to look at <span class="math inline">\(adjusted \ R^2\)</span>, because it adjusts for the number of variables in our model and makes comparison of multiple models easier. There are a couple more important insights gained from this analysis:</p>
<ul>
<li><p>All variables appear to be significant and therefore help to explain new cases.</p></li>
<li><p>The variables <code>masks</code>, <code>movements</code> and <code>gatherings</code> seem to reduce <code>new_cases</code>, i.e. they have negative estimates (<span class="math inline">\(\beta\)</span>).</p></li>
<li><p>However, <code>schools</code>, <code>businesses</code>, <code>travel</code> have a positive effect on <code>new_cases</code>.</p></li>
</ul>
<p>Especially the last point might appear confusing. How can measures taken increase the number of new COVID cases? Should we avoid them? What we have not considered in our regression is the fact that measures might be put in place to reduce the number of new cases rather than to prevent them. Thus, it might not be the case that <code>schools</code>, <code>businesses</code> and <code>travel</code> predict higher <code>new_cases</code>, but rather the opposite, i.e. due to higher <code>new_cases</code> the measures for <code>schools</code>, <code>businesses</code> and <code>travel</code> were tightened, which later on (with a time lag) led to lower <code>new_cases</code>. Thus, the relationships might be a bit more complicated, but to keep things simple, we accept the fact that with our data we face certain limitations (as is usually the case).</p>
<p>However, there are a couple of things we overlooked when running this regression. If you are familiar with regressions already, you might have been folding the hands over your face and bursted into tears about the blasphemeous approach to linear regression modelling. Let me course-correct at this point.</p>
<p>Similar to other parametric approaches to conducting research, we need to test for sources of bias, linearity, normality and homogeneity of variance (or the unpronounceable word ‘homoscedasticity’). Since multiple regressions consider more than one variable we have to consider these crieria in light of other variables. As such, we have to draw on different tools to assess our data. There are certain pre- and post-tests we have to perform to fully assess and develop a multiple regression model:</p>
<ul>
<li><p><em>pre-test</em>: We need to consider whether there are any outliers and whether all variables are parametric.</p></li>
<li><p><em>post-test</em>: Do our independent variables correlate very strongly with each other, i.e. are there issues of multiple collinearity.</p></li>
</ul>
<p>We already covered aspects of linearity, normality and homogeneity of variance. However, outliers and collinearity have to be reconsidered for multiple regressions.</p>
<div id="outliers-in-multiple-regressions" class="section level3" number="12.2.1">
<h3><span class="header-section-number">12.2.1</span> Outliers in multiple regressions</h3>
<p>While it should be fairly clear by now why we need to handle outliers (remember Chapter <a href="sources-of-bias.html#dealing-with-outliers">9.5</a>), the approach we take is somewhat different when we need to consider multiple variables at once. Instead of identifying outliers for each variable independently, we have to consider the interplay of variables as well. In other words, we need to find out how an outlier in our independent variable affects the overall model rather than just on single other variable. In short, we need a different technique to assess outliers. By now, you might not be shocked to find out that there is more than one way of identifying outliers in regressions and many different ways to compute them in R. <span class="citation">(<a href="#ref-cohen2014applied" role="doc-biblioref">P. Cohen, West, and Aiken 2014</a>)</span> distinguishes between where one can find outliers in the model as summarised in Table <a href="regression.html#tab:outliers-in-multiple-regressions">12.1</a>. I offer a selection of possible ways of computing the relevant statistics, but this list is not exhaustive. For example, many of these statistics can also be found by using <code>influence.measures()</code>.</p>
<table>
<caption><span id="tab:outliers-in-multiple-regressions">Table 12.1: </span>Outlier detection in multiple regressions</caption>
<colgroup>
<col width="17%" />
<col width="26%" />
<col width="56%" />
</colgroup>
<thead>
<tr class="header">
<th>Outlier in?</th>
<th>Measures</th>
<th>function in R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Dependent variable</em></td>
<td><ul>
<li>Internally studentized residuals</li>
</ul></td>
<td><ul>
<li><code>rstandard()</code> or <code>fortify()</code></li>
</ul></td>
</tr>
<tr class="even">
<td><em>Dependent variable</em></td>
<td><ul>
<li>Externally studentized residuals</li>
</ul></td>
<td><ul>
<li><code>rstudent()</code></li>
</ul></td>
</tr>
<tr class="odd">
<td><em>Independent variable</em></td>
<td><ul>
<li>Leverage</li>
</ul></td>
<td><ul>
<li><code>hatvalues()</code> or <code>fortify()</code></li>
</ul></td>
</tr>
<tr class="even">
<td><em>Independent variable</em></td>
<td><ul>
<li>Mahalanobis distance</li>
</ul></td>
<td><ul>
<li><code>mahalanobis()</code><a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> or <code>mahalanobis_distance()</code><a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></li>
</ul></td>
</tr>
<tr class="odd">
<td><em>Entire model</em></td>
<td><p><em>Global measures of influence</em></p>
<ul>
<li><p>DFFITS,</p></li>
<li><p>Cook’s d</p></li>
</ul></td>
<td><p><em>Global measures of influence</em></p>
<ul>
<li><p><code>dffits()</code></p></li>
<li><p><code>cooks.distance()</code> or <code>fortify()</code></p></li>
</ul></td>
</tr>
<tr class="even">
<td><em>Entire model</em></td>
<td><p><em>Specific measures of influence:</em></p>
<ul>
<li>DFBETAS</li>
</ul></td>
<td><p><em>Specific measures of influence:</em></p>
<ul>
<li><code>dfbetas()</code></li>
</ul></td>
</tr>
</tbody>
</table>
<p>While it might be clear why we need to use different approaches to find outliers in different components of our model, this might be less clear when evaluating outliers that affect the entire model. We distinguish between <em>global measures of influence</em>, which identify how a single observation affects the quality of the entire model, and <em>specific measures of influence</em>, which identify how a single observation affects each individual independent variable, i.e. its regression coefficients denoted as <span class="math inline">\(\beta\)</span>. It is recommended to look at all different measures of outliers before venturing ahead to performing a linear multiple regression. Going through the entire set of possible outliers would way beyond the scope of this book. So, I will focus on five popular measures which cover all three categories:</p>
<ul>
<li><p>Dependent variable: Externally studentized residuals</p></li>
<li><p>Independent variable: Leverage and Mahalanobis distance</p></li>
<li><p>Entire model: Cook’s d, DFBETAS</p></li>
</ul>
<p>The approach taken is the same for the other outlier detection methods. Thus, it should be fairly simple to reproduce these as well after having finished the chapters below.</p>
<div id="outliers-in-the-dependent-variable" class="section level4" number="12.2.1.1">
<h4><span class="header-section-number">12.2.1.1</span> Outliers in the dependent variable</h4>
<p>Irrespective of whether we look at independent or dependent variables, we always want to know whether there are extreme values present. Here I will use the externally studentized residual which ’is the preferred statistic to use to identify cases whose […] values are highly discrepant from their predicted values <span class="citation">(<a href="#ref-cohen2014applied" role="doc-biblioref">P. Cohen, West, and Aiken 2014, 401</a>)</span>.</p>
<p>First we need to compute the residuals for our model as a new column in our dataset. Since we also want to use other methods to investigate outliers we can use the function <code>fortify()</code> which will add some of the later indicators as well and create a <code>tibble</code> which only includes the variables from our model. One function to do a lot of things at once. In a second step we hadd the studentized residuals using <code>rstudent()</code>.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="regression.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a tibble with some pre-computed stats</span></span>
<span id="cb22-2"><a href="regression.html#cb22-2" aria-hidden="true" tabindex="-1"></a>m1_outliers <span class="ot">&lt;-</span> <span class="fu">fortify</span>(m1) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb22-3"><a href="regression.html#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(m1_outliers)</span></code></pre></div>
<pre><code>## Rows: 1,188
## Columns: 13
## $ new_cases  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ masks      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ movements  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ gatherings &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ schools    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ businesses &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ travel     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ .hat       &lt;dbl&gt; 0.005493624, 0.005493624, 0.005493624, 0.005493624, 0.00549…
## $ .sigma     &lt;dbl&gt; 10060.85, 10060.85, 10060.85, 10060.85, 10060.85, 10060.85,…
## $ .cooksd    &lt;dbl&gt; 5.243271e-05, 5.243271e-05, 5.243271e-05, 5.243271e-05, 5.2…
## $ .fitted    &lt;dbl&gt; -2585.184, -2585.184, -2585.184, -2585.184, -2585.184, -258…
## $ .resid     &lt;dbl&gt; 2585.184, 2585.184, 2585.184, 2585.184, 2585.184, 2585.184,…
## $ .stdresid  &lt;dbl&gt; 0.2577653, 0.2577653, 0.2577653, 0.2577653, 0.2577653, 0.25…</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="regression.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the externally studentized residuals</span></span>
<span id="cb24-2"><a href="regression.html#cb24-2" aria-hidden="true" tabindex="-1"></a>m1_outliers <span class="ot">&lt;-</span> m1_outliers <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="regression.html#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.studresid =</span> <span class="fu">rstudent</span>(m1))</span>
<span id="cb24-4"><a href="regression.html#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(m1_outliers)</span></code></pre></div>
<pre><code>## Rows: 1,188
## Columns: 14
## $ new_cases  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ masks      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ movements  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ gatherings &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ schools    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ businesses &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ travel     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ .hat       &lt;dbl&gt; 0.005493624, 0.005493624, 0.005493624, 0.005493624, 0.00549…
## $ .sigma     &lt;dbl&gt; 10060.85, 10060.85, 10060.85, 10060.85, 10060.85, 10060.85,…
## $ .cooksd    &lt;dbl&gt; 5.243271e-05, 5.243271e-05, 5.243271e-05, 5.243271e-05, 5.2…
## $ .fitted    &lt;dbl&gt; -2585.184, -2585.184, -2585.184, -2585.184, -2585.184, -258…
## $ .resid     &lt;dbl&gt; 2585.184, 2585.184, 2585.184, 2585.184, 2585.184, 2585.184,…
## $ .stdresid  &lt;dbl&gt; 0.2577653, 0.2577653, 0.2577653, 0.2577653, 0.2577653, 0.25…
## $ .studresid &lt;dbl&gt; 0.2576634, 0.2576634, 0.2576634, 0.2576634, 0.2576634, 0.25…</code></pre>
<p>With our dataset ready for plotting we can do exactly that.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="regression.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an ID column</span></span>
<span id="cb26-2"><a href="regression.html#cb26-2" aria-hidden="true" tabindex="-1"></a>m1_outliers <span class="ot">&lt;-</span> m1_outliers <span class="sc">%&gt;%</span> <span class="fu">rownames_to_column</span>()</span>
<span id="cb26-3"><a href="regression.html#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="regression.html#cb26-4" aria-hidden="true" tabindex="-1"></a>m1_outliers <span class="sc">%&gt;%</span></span>
<span id="cb26-5"><a href="regression.html#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> rowname,</span>
<span id="cb26-6"><a href="regression.html#cb26-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> .studresid)) <span class="sc">+</span></span>
<span id="cb26-7"><a href="regression.html#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.5</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Plot%20externally%20studentized%20residuals-1.png" width="672" /></p>
<p>The values of the externally studentized residuals can be positive or negative. All we need to know now is which values count as outliers and which ones do not. <span class="citation"><a href="#ref-cohen2014applied" role="doc-biblioref">P. Cohen, West, and Aiken</a> (<a href="#ref-cohen2014applied" role="doc-biblioref">2014</a>)</span> (p. 401) provides some guidance:</p>
<ul>
<li><p>general: <span class="math inline">\(outlier = \pm 2\)</span></p></li>
<li><p>bigger samples: <span class="math inline">\(outlier = \pm 3\)</span> or <span class="math inline">\(\pm 3.5\)</span> or <span class="math inline">\(\pm 4\)</span></p></li>
</ul>
<p>As you can tell, it is a matter of well-informed personal judgement. Our dataset consists of over 1200 observations. As such, the dataset certainly counts as large. We can take a look and see how many outliers we would get for each of the benchmarks.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="regression.html#cb27-1" aria-hidden="true" tabindex="-1"></a>out_detect <span class="ot">&lt;-</span> m1_outliers <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="regression.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pm_2 =</span> <span class="fu">ifelse</span>(<span class="fu">abs</span>(.studresid) <span class="sc">&gt;</span> <span class="dv">2</span>, <span class="st">&quot;yes&quot;</span>, <span class="st">&quot;no&quot;</span>),</span>
<span id="cb27-3"><a href="regression.html#cb27-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">pm_3 =</span> <span class="fu">ifelse</span>(<span class="fu">abs</span>(.studresid) <span class="sc">&gt;</span> <span class="dv">3</span>, <span class="st">&quot;yes&quot;</span>, <span class="st">&quot;no&quot;</span>),</span>
<span id="cb27-4"><a href="regression.html#cb27-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">pm_35 =</span> <span class="fu">ifelse</span>(<span class="fu">abs</span>(.studresid) <span class="sc">&gt;</span> <span class="fl">3.5</span>, <span class="st">&quot;yes&quot;</span>, <span class="st">&quot;no&quot;</span>),</span>
<span id="cb27-5"><a href="regression.html#cb27-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">pm_4 =</span> <span class="fu">ifelse</span>(<span class="fu">abs</span>(.studresid) <span class="sc">&gt;</span> <span class="dv">4</span>, <span class="st">&quot;yes&quot;</span>, <span class="st">&quot;no&quot;</span>))</span>
<span id="cb27-6"><a href="regression.html#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="regression.html#cb27-7" aria-hidden="true" tabindex="-1"></a>out_detect <span class="sc">%&gt;%</span> <span class="fu">count</span>(pm_2)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   pm_2      n
##   &lt;chr&gt; &lt;int&gt;
## 1 no     1135
## 2 yes      53</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="regression.html#cb29-1" aria-hidden="true" tabindex="-1"></a>out_detect <span class="sc">%&gt;%</span> <span class="fu">count</span>(pm_3)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   pm_3      n
##   &lt;chr&gt; &lt;int&gt;
## 1 no     1170
## 2 yes      18</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="regression.html#cb31-1" aria-hidden="true" tabindex="-1"></a>out_detect <span class="sc">%&gt;%</span> <span class="fu">count</span>(pm_35)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   pm_35     n
##   &lt;chr&gt; &lt;int&gt;
## 1 no     1175
## 2 yes      13</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="regression.html#cb33-1" aria-hidden="true" tabindex="-1"></a>out_detect <span class="sc">%&gt;%</span> <span class="fu">count</span>(pm_4)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   pm_4      n
##   &lt;chr&gt; &lt;int&gt;
## 1 no     1181
## 2 yes       7</code></pre>
<p>The results indicate we could have as many as 53 outliers and as little as 7. It becomes apparent that choosing the right threshold is a tricky undertaking. Let’s plot the data again in an easier way to read and add some of the thresholds. I skip <code>3.5</code>, since it is very close to <code>3</code>. I also reorder the observations (i.e. the x axis) based on <code>.studresid</code> using <code>reorder()</code>.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="regression.html#cb35-1" aria-hidden="true" tabindex="-1"></a>m1_outliers <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="regression.html#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(rowname, .studresid),</span>
<span id="cb35-3"><a href="regression.html#cb35-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> .studresid)) <span class="sc">+</span></span>
<span id="cb35-4"><a href="regression.html#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="regression.html#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="regression.html#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>), <span class="at">col =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-7"><a href="regression.html#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Plotting%20the%20number%20of%20outliers%20externally%20studentized%20residuals-1.png" width="672" /></p>
<p>At this point, it is a matter of choosing the threshold that you feel is most appropriate. More importantly, though, you have to make sure you are transparent in your choices and provide some explanations around your decision-making. For example, a threshold of <code>2</code> appears a bit too harsh for my taste and identifies too many observations as outliers. Using the orange threshold of <code>3</code> seems to capture most outliers, because we can also visually see how the dots start to look less like a line and separate out more strongly. Besides, a threshold of <code>3</code> seems also more suitable for larger datasets. Since we have an id column (i.e. <code>rownames</code>) we can also store our outliers in a separate object to easily reference it later for comparisons with other measures. You will see later why this is handy to have.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="regression.html#cb36-1" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> out_detect <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="regression.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(rowname, pm_3) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="regression.html#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">studresid =</span> pm_3)</span></code></pre></div>
<p>There are still more diagnostic steps we have to take before we make a final decision on which observations we want to remove or deal with in other ways (see also Chapter <a href="sources-of-bias.html#dealing-with-outliers">9.5</a>.</p>
</div>
<div id="outliers-in-the-independent-variables" class="section level4" number="12.2.1.2">
<h4><span class="header-section-number">12.2.1.2</span> Outliers in the independent variables</h4>
<p>To identify outliers in the independent variables we can either use, for example, <em>Leverage scores</em>, or use the <em>Mahalanobis distances</em>. Both are legitimate approaches and can be computed very easily.</p>
<p>For the leverage scores, we can find them already in our <code>fortify()</code>-ed dataset <code>m1_outliers</code>. They are in the column <code>.hat</code>. An outlier is defined by the distance from the average leverage value, i.e. the further the distance of an observation from this average leverage, the more likely we have to classify it as an outlier. The average leverage is computed as follows:</p>
<div id="average-leverage-equation" align="center">
<p><span class="math inline">\(average\ leverage = \frac{k + 1}{n}\)</span></p>
</div>
<p>In this equation, <em>k</em> stands for the number of predictors (i.e. 6) and <em>n</em> for the number of observations (i.e. 1188). Therefore, our average leverage can be computed as follows:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="regression.html#cb37-1" aria-hidden="true" tabindex="-1"></a>(avg_lvg <span class="ot">&lt;-</span> (<span class="dv">6</span> <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">1188</span>)</span></code></pre></div>
<pre><code>## [1] 0.005892256</code></pre>
<p>Also for this indicator we find different approaches to setting cut-off points. While <span class="citation"><a href="#ref-hoaglin1978hat" role="doc-biblioref">Hoaglin and Welsch</a> (<a href="#ref-hoaglin1978hat" role="doc-biblioref">1978</a>)</span> argue that a distance twice the average counts as an outlier, <span class="citation"><a href="#ref-stevens2012applied" role="doc-biblioref">Stevens</a> (<a href="#ref-stevens2012applied" role="doc-biblioref">2012</a>)</span> (p.105) suggests that values three times higher than the average leverage will negatively affect the model. The rationale is the same as for the externally studentized residuals: If the thresholds are too low, we might find ourselves with many observations which we would have to further investigate. This might not always be possible or even desirable. However, this should not imply that many outliers are not worth checking. Instead, if there are many, one would have to raise questions about the model itself and whether an important variable needs adding to explain a series of observations that appear to be somewhat ‘off.’</p>
<p>Let’s plot the leverages and use <span class="citation"><a href="#ref-stevens2012applied" role="doc-biblioref">Stevens</a> (<a href="#ref-stevens2012applied" role="doc-biblioref">2012</a>)</span> benchmark to draw our reference line.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="regression.html#cb39-1" aria-hidden="true" tabindex="-1"></a>m1_outliers <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="regression.html#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(rowname, .hat),</span>
<span id="cb39-3"><a href="regression.html#cb39-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> .hat)) <span class="sc">+</span></span>
<span id="cb39-4"><a href="regression.html#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb39-5"><a href="regression.html#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">3</span><span class="sc">*</span>avg_lvg, <span class="at">col =</span> <span class="st">&quot;orange&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Plotting%20leverages-1.png" width="672" /></p>
<p>As before, we want to know which observations fall beyond the threshold.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="regression.html#cb40-1" aria-hidden="true" tabindex="-1"></a>new_outliers <span class="ot">&lt;-</span> m1_outliers <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="regression.html#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">avglvg =</span> <span class="fu">ifelse</span>(.hat <span class="sc">&gt;</span> <span class="dv">3</span><span class="sc">*</span>avg_lvg, <span class="st">&quot;yes&quot;</span>, <span class="st">&quot;no&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="regression.html#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(rowname, avglvg)</span>
<span id="cb40-4"><a href="regression.html#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="regression.html#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Add new results to our reference list</span></span>
<span id="cb40-6"><a href="regression.html#cb40-6" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> <span class="fu">left_join</span>(outliers, new_outliers, <span class="at">by =</span> <span class="st">&quot;rowname&quot;</span>)</span></code></pre></div>
<p>If you look at our reference object <code>outliers</code> now, you will notice that there is only one observation that was detected by both methods. Thus, it very much depends on where we look for outliers, i.e. dependent variable or independent variable.</p>
<p>The second method I will cover in this section is the Mahalanobis distance. Luckily the <code>rstatix</code> package includes a handy function <code>mahalanobis_distance()</code> which automatically detects outliers and presents them to us.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="regression.html#cb41-1" aria-hidden="true" tabindex="-1"></a>mhnbs_outliers <span class="ot">&lt;-</span> m1_outliers <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="regression.html#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(new_cases<span class="sc">:</span>travel) <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="regression.html#cb41-3" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">mahalanobis_distance</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb41-4"><a href="regression.html#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>() <span class="sc">%&gt;%</span></span>
<span id="cb41-5"><a href="regression.html#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(rowname, mahal.dist, is.outlier) <span class="sc">%&gt;%</span></span>
<span id="cb41-6"><a href="regression.html#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">mhnbs =</span> is.outlier)</span>
<span id="cb41-7"><a href="regression.html#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="regression.html#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Add new results to our reference list</span></span>
<span id="cb41-9"><a href="regression.html#cb41-9" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> <span class="fu">left_join</span>(outliers, mhnbs_outliers, <span class="at">by =</span> <span class="st">&quot;rowname&quot;</span>)</span>
<span id="cb41-10"><a href="regression.html#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="regression.html#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="co"># We need to remove mahal.dist because it does not indicate</span></span>
<span id="cb41-12"><a href="regression.html#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="co"># whether a value is an outlier #data-cleaning</span></span>
<span id="cb41-13"><a href="regression.html#cb41-13" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> outliers <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>mahal.dist)</span></code></pre></div>
<p>While very convenient, it does pick the cut-off point for us. As we have learned so far, picking the ‘right’ cut-off point is important. Since the values follow a chi-square distribution, we can determine the cut-off points based on the relevant critical value at the chosen p value. R has a function which allows to find the critical value for our model, i.e. <code>qchisq()</code>.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="regression.html#cb42-1" aria-hidden="true" tabindex="-1"></a>(mhnbs_th <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="at">p =</span> <span class="fl">0.05</span>,</span>
<span id="cb42-2"><a href="regression.html#cb42-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">df =</span> <span class="dv">6</span>,</span>
<span id="cb42-3"><a href="regression.html#cb42-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">lower.tail =</span> <span class="cn">FALSE</span>))</span></code></pre></div>
<pre><code>## [1] 12.59159</code></pre>
<p>The <code>p</code> value reflects the probability we are willing to accept that our result is significant/not significant. The <code>df</code> refers to the degrees of freedom, which in this case relates to the number of independent variables, i.e. 6. Thus, it is fairly simple to identify a cut-off point yourself by choosing the p value you consider most appropriate. The function <code>mahalanobis_distance()</code> assumes <span class="math inline">\(p = 0.01\)</span>.</p>
<p>If we wanted to plot outliers like we did before, we can reuse our code from above and replace it with the relevant new variables.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="regression.html#cb44-1" aria-hidden="true" tabindex="-1"></a>mhnbs_outliers <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="regression.html#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(rowname, mahal.dist),</span>
<span id="cb44-3"><a href="regression.html#cb44-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> mahal.dist)) <span class="sc">+</span></span>
<span id="cb44-4"><a href="regression.html#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb44-5"><a href="regression.html#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> mhnbs_th, <span class="at">col =</span> <span class="st">&quot;orange&quot;</span>)</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Plotting%20Mahalanobis%20distance%20scores-1.png" width="672" /></p>
<p>We can notice that the Mahalanobis distance identifies less outliers compared to the leverage, but the same ones. Thus, whether you really need to use both approaches for the same study is questionable and likely redundant. Still, in a few edge cases, you might want to double-check the results, especially when you feel uncertain which observations should be dealt with later.</p>
<p>Besides looking at each side of the regression separately, we might also want to consider whether removing an observation significantly changes the <span class="math inline">\(\beta\)</span> estimates. This is done with outlier detection diagnostics which consider the entire model.</p>
</div>
<div id="outlier-detection-global-measures" class="section level4" number="12.2.1.3">
<h4><span class="header-section-number">12.2.1.3</span> Outlier detection considering the entire model: Global measures</h4>
<p>To assess the global impact of outliers on the entirety of a regression model, Cook’s d <span class="citation">(<a href="#ref-cook1982residuals" role="doc-biblioref">Cook and Weisberg 1982</a>)</span> is a popular method in the Social Sciences. It measures to which extend a single observation can affect the predictive power of our model to explain all other observations. Obviously, we do not wish to keep observations that make it more difficult to predict most of the other observations correctly. However, as shown in Table <a href="regression.html#tab:outliers-in-multiple-regressions">12.1</a>, there are different approaches to this, but some are somewhat redundant. For example, <span class="citation"><a href="#ref-cohen2014applied" role="doc-biblioref">P. Cohen, West, and Aiken</a> (<a href="#ref-cohen2014applied" role="doc-biblioref">2014</a>)</span> highlight that DDFITS and Cook’s d are ‘interchangeable statistics’ (p. 404). Thus, there is no point in demonstrating both since they function in a similar way. Your decision might be swayed by the preferences of a publisher, lecturer, supervisor or reviewer. Here, I will focus on Cook’s d since it was I see most frequently used in my own field. By all means, feel encouraged to go the extra mile and perform the same steps for the DDFITS.</p>
<p>The good news, <code>fortify()</code> automatically added <code>.cooksd</code> to our dataset <code>m1_outliers</code>. Thus, we cannot only compute whether outliers exist, but also inspect them visually as we did before. A good starting point to find outliers via the Cook’s D is to plot its distribution.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="regression.html#cb45-1" aria-hidden="true" tabindex="-1"></a>m1_outliers <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="regression.html#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> rowname,</span>
<span id="cb45-3"><a href="regression.html#cb45-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> .cooksd)) <span class="sc">+</span></span>
<span id="cb45-4"><a href="regression.html#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code></pre></div>
<p><img src="r_for_non_programmers_files/figure-html/Plotting%20Cooks%20d-1.png" width="672" /></p>
<p>Inspecting this barplot, we can tell that there are some observations that have much higher <code>.cooksd</code> values than any other observations. Again, we first need to decide on a benchmark to determine whether we can consider these values as outliers. If we follow <span class="citation"><a href="#ref-cook1982residuals" role="doc-biblioref">Cook and Weisberg</a> (<a href="#ref-cook1982residuals" role="doc-biblioref">1982</a>)</span>, values that are higher than <span class="math inline">\(d &gt; 1\)</span> require reviewing. Looking at our plot, none of the observations reaches <code>1</code> and therefore we would have no need to investigate outliers. Alternatively, <span class="citation"><a href="#ref-cohen2014applied" role="doc-biblioref">P. Cohen, West, and Aiken</a> (<a href="#ref-cohen2014applied" role="doc-biblioref">2014</a>)</span> suggest that other benchmarks are also worth considering, for example based on the critical value of an F distribution, which we can determine with the function <code>qf()</code>, which requires us to determine two degrees of freedom (<span class="math inline">\(df_1\)</span> and <span class="math inline">\(df_2\)</span>) and a p value. To determine these values <span class="citation"><a href="#ref-cohen2014applied" role="doc-biblioref">P. Cohen, West, and Aiken</a> (<a href="#ref-cohen2014applied" role="doc-biblioref">2014</a>)</span> suggests <span class="math inline">\(p = 0.5\)</span> and the following formulas to determine the correct <span class="math inline">\(df\)</span>:</p>
<div id="critical-value-cooks-d" align="center">
<p><span class="math inline">\(df_1 = k +1\)</span></p>
<p><span class="math inline">\(df_2 = n - k - 1\)</span></p>
</div>
<p>Similar to the critical value for <a href="regression.html#average-leverage-equation" title="average leverage">average leverage</a>, <span class="math inline">\(k\)</span> reflects the number of predictors, and <span class="math inline">\(n\)</span> refers to the sample size. Thus, we can determine the critical value, and therefore our cut-off point as follows:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="regression.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qf</span>(<span class="at">p =</span> <span class="fl">0.5</span>,</span>
<span id="cb46-2"><a href="regression.html#cb46-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">df1 =</span> <span class="dv">6</span><span class="sc">+</span><span class="dv">1</span>,</span>
<span id="cb46-3"><a href="regression.html#cb46-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">df2 =</span> <span class="dv">1188-6-1</span>)</span></code></pre></div>
<pre><code>## [1] 0.9070612</code></pre>
<p>Also this score would imply that we have no particular outliers to consider, because the highest value in <code>.cooksd</code> is 0.0733569</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="regression.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Any Cook&#39;s d &gt;1?</span></span>
<span id="cb48-2"><a href="regression.html#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="regression.html#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Any Cook&#39;s d &gt; median?</span></span></code></pre></div>
</div>
<div id="outlier-detection-specific-measures" class="section level4" number="12.2.1.4">
<h4><span class="header-section-number">12.2.1.4</span> Outlier detection considering the entire model: Specific measures</h4>
</div>
</div>
</div>
<div id="hierarchical-regression" class="section level2" number="12.3">
<h2><span class="header-section-number">12.3</span> Hierarchical regression</h2>
</div>
<div id="moderated-regressions" class="section level2" number="12.4">
<h2><span class="header-section-number">12.4</span> Moderated regression</h2>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-boehmke2019hands" class="csl-entry">
Boehmke, Brad, and Brandon Greenwell. 2019. <em>Hands-on Machine Learning with r</em>. Chapman; Hall/CRC.
</div>
<div id="ref-cohen1988statistical" class="csl-entry">
Cohen, Jacob. 1988. <span>“Statistical Power Analysis for the Behavioral Sciences New York.”</span> <em>NY: Academic</em>, 54.
</div>
<div id="ref-cohen2014applied" class="csl-entry">
Cohen, Patricia, Stephen G West, and Leona S Aiken. 2014. <em>Applied Multiple Regression/Correlation Analysis for the Behavioral Sciences</em>. Psychology press.
</div>
<div id="ref-cook1982residuals" class="csl-entry">
Cook, R Dennis, and Sanford Weisberg. 1982. <em>Residuals and Influence in Regression</em>. New York: Chapman; Hall.
</div>
<div id="ref-gelman2020regression" class="csl-entry">
Gelman, Andrew, Jennifer Hill, and Aki Vehtari. 2020. <em>Regression and Other Stories</em>. Cambridge University Press.
</div>
<div id="ref-hoaglin1978hat" class="csl-entry">
Hoaglin, David C, and Roy E Welsch. 1978. <span>“The Hat Matrix in Regression and ANOVA.”</span> <em>The American Statistician</em> 32 (1): 17–22.
</div>
<div id="ref-stevens2012applied" class="csl-entry">
Stevens, James P. 2012. <em>Applied Multivariate Statistics for the Social Sciences</em>. Routledge.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Germany is called ‘Deutschland’ in German, hence the abbreivation ‘DEU’ according to the <a href="https://www.iso.org/obp/ui/#iso:code:3166:DE" target="blank" title="ISO country code">ISO country code</a>.<a href="regression.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>This function does not take the model as an attribute, but instead requires the data, the column means and the covariance. Thus, we have to specify this function in the following way: <code>mahalanobis(data, colMeans(data), cov(data))</code><a href="regression.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>Function from <code>rstatix</code> package which automatically classifies values as outliers for us.<a href="regression.html#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="comparing-groups.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mixed-methods-research-analysing-qualitative-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["r_for_non_programmers.pdf", "r_for_non_programmers.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
